README.md
specifications/generic-lock-example.json
src/apps/default.nix
src/apps/translators-cli.py
src/builders/default.nix
src/builders/python/simple-builder/default.nix
src/default.nix
src/fetchers/combined-fetcher.nix
src/fetchers/default-fetcher.nix
src/fetchers/default.nix
src/translators/python/external-pip/generate-generic-lock.py

Now a user can call `translate` passing `--combined` which will ommit storing individual hashes and instead store one big hash for all sources.
For large packages with several thousand dependencies, this can be a useful feature.
This feature is generic, so an individual translator module doesn't need to support this explicitly.
This works in a way, so the override interface for individual fetch calls doesn't break.
The exact builder scripts of the underlying fetchers are re-used with the provided parameters and executed one after another inside a single FOD build.

add support for opt-in FOD fetching

---

docs/translators.md
flake.nix
specifications/generic-lock-example.json
specifications/translator-call-example.json
src/apps/cli.py
src/apps/default.nix
src/default.nix
src/translators/default.nix
src/translators/nodejs/pure/npmlock2nix/default.nix
src/translators/python/impure/pip/default.nix
src/utils.nix

From now on the user does not need to select the translator anymore.
It is sufficient to just pass source trees or files and the framework will automatically figure out which translator to use.

Add feature: autoselect translator

---

src/apps/cli/commands/add.py
src/apps/cli/utils.py
src/builders/nodejs/granular/default.nix
src/builders/nodejs/granular/fix-package.py
src/translators/nodejs/pure/package-lock/default.nix

Done:
- builder: just skip cyclic dependencies instead of delegating to combined builder
- builder: fix bug: crash if `bin` field in package.json is empty string
- package-lock translator: allow `name` to be specified through CLI

nodejs builder/translator and CLI improvements

---

src/apps/cli/commands/add.py
src/apps/cli/utils.py
src/builders/nodejs/granular/default.nix
src/builders/nodejs/granular/fix-package.py
src/default.nix
src/templates/builders/default.nix
src/translators/nodejs/pure/package-lock/default.nix
src/utils/override.nix
src/utils/parsing.nix

Done:
- handle more ways of dependency references in package-lock.json
- handle `github:` git urls.
- simplify applying overrides in builder by introducing new helper `produceDerivation`
- fix: $buildScript execution

Improve nodejs translators and API of builders

---

src/fetchers/crates-io/default.nix
src/fetchers/default-fetcher.nix
src/fetchers/default.nix
src/fetchers/npm/default.nix
src/fetchers/pypi-sdist/default.nix
src/specifications/dream-lock-schema.json
src/translators/rust/pure/cargo-lock/default.nix
src/utils/translator.nix

This PR changes fetcher interface so that both version and pname are now passed to fetchers. This is useful since we can drop `pname` and `version` from source constructors, and it makes the lock have less duplicated data. It also adds warnings if a source constructor uses `pname` and `version` fields, since they will be overrided by dream2nix.

feat: pass version and pname to fetchers

---

overrides/nodejs/default.nix
overrides/nodejs/element-desktop/tsconfig.json
overrides/nodejs/enhanced-resolve/npm-preserve-symlinks-v4.patch
overrides/nodejs/enhanced-resolve/npm-preserve-symlinks-v5.patch
overrides/nodejs/enhanced-resolve/respect-node-path-v5.patch
overrides/nodejs/webpack-cli/remove-webpack-check.patch
overrides/nodejs/webpack/remove-webpack-cli-check.patch

Overrides contain essential fixups for build toolchain. Therefore it doesn't really make sense to deliver dream2nix without those.

move overrides from dreampks -> dream2nix

---

flake.nix
src/apps/cli/commands/add.py
src/apps/cli/default.nix
src/builders/nodejs/granular/default.nix
src/default.nix
src/translators/nodejs/pure/package-lock/default.nix
src/translators/nodejs/pure/yarn-lock/default.nix
src/utils/config.nix
src/utils/dream-lock.nix
src/utils/override.nix

This adds basic support for handling projects that contain multiple sources of translatable metadata.
For example nodjs projects which contain multiple `package-lock.json` files in different directories can now be handled.
The CLI now accepts multiple source arguments. The first one will be the main project. All other sources will be translated into sub-directories aside the main `dream-lock.json`.

feature: support multiple packages per source

---

src/translators/rust/pure/cargo-lock/default.nix

This fixes an issue with `Cargo.toml` files that don't contain packages be picked up by the `findCratePath` function for the `path` source constructor.

fix(translator/cargo-lock): use cargoPackages instead of cargoTomls while searching for crates

---

overrides/nodejs/default.nix
src/apps/cli/commands/add.py
src/apps/cli/utils.py
src/builders/nodejs/granular/default.nix
src/builders/nodejs/granular/fix-package.py
src/builders/nodejs/granular/install-deps.py
src/translators/default.nix
src/translators/go/impure/gomod2nix/translate.nix
src/translators/nodejs/pure/yarn-lock/default.nix
src/utils/translator.nix

This adds a `--sub-dirs` flag to the CLI.
It simplifies translation of projects containing several sources of translatable metadata.
This is suitable if the a project contains several sub projects which can be translated independently.
An example would be a project which contains more than one lock-file.

Recursive translation of sub-projects in CLI via `--sub-dirs`

---

src/translators/nodejs/pure/yarn-lock/parser.nix

Sometimes there will be unquoted strings (eg: latest) in dependecy
positions. They are resolved elsewhere but results in a parse error.

Parse unquoted strings in yarn.lock

---

src/builders/rust/build-rust-package/default.nix
src/default.nix
src/specifications/subsystems/rust/dream.lock.example.json
src/translators/rust/pure/cargo-lock/default.nix
src/utils/dream-lock.nix

Before, git sources weren't vendored properly. This PR:
- writes vendor entries to .cargo/config before building
- writes .cargo-checksum in vendored sources for git deps
- handles workspace git dependencies where the crates are in subdirectories
- copies sources instead of symlinking them so we can write the cargo checksums

fix(rust): handle git source vendoring properly

---

flake.nix

I'm using `aarch64-darwin`. This allows me to run the `dream2nix` cli.

Add darwin to architecture list

---

src/apps/cli/commands/add.py
src/apps/cli/commands/update.py
src/apps/cli/default.nix
src/builders/nodejs/granular/default.nix
src/builders/nodejs/node2nix/default.nix
src/builders/python/simple-builder/default.nix
src/builders/rust/build-rust-package/default.nix
src/default.nix
src/fetchers/default-fetcher.nix
src/specifications/dream-lock-example.json
src/specifications/dream-lock-schema.json
src/specifications/subsystems/rust/dream.lock.example.json
src/templates/builders/default.nix
src/templates/translators/pure.nix
src/translators/go/impure/gomod2nix/translate.nix
src/translators/nodejs/pure/package-lock/default.nix
src/translators/nodejs/pure/yarn-lock/default.nix
src/translators/python/impure/pip/generate-dream-lock.py
src/translators/rust/pure/cargo-lock/default.nix
src/utils/dream-lock.nix
src/utils/translator.nix

This changes the structure of the dream-lock.json to support a list of top level packages instead of a single top level package.
Despite these changes, some parts of the framework still depend on `defaultPackage` not being null or unset.
That means there is still some work left to, but from here on we can smoothly transition away from enforcing a `defaultPackage`.
removed dream-lock fields:
- translator (currently covered by translatorParams)
- translatedBy (currently covered by translatorParams)
- mainPackageName
- mainPackageVersion
added dream-lock fields:
- defaultPackage  (equivalent to old `mainPackageName`)
- packages
Other changes done on the rust subsytem:
- fix a bug in the rust translator where the path `path-like` sources was wrong whenever the path length is greater 1. …

dream-lock: support multiple top-level packages

---

README.md
flake.nix
src/apps/cli/commands/add.py
src/apps/cli/default.nix
src/default.nix
src/lib.nix
src/specifications/dream-lock-schema.json
src/translators/default.nix
src/utils/config.nix
src/utils/default.nix
src/utils/dream-lock.nix
tests/pure/projects.nix

With this, there is only one recommended way of using dream2nix which is through the flake shown in the readme.
Until now, using dream2nix via the flake was only possible if the project could be translated via a `pure` translator. Using the `impure` translation required the user to mess with the CLI.
With this patch, there will be a flakes based UX also for `impure` translation.
If a project requires impure translation, nix evaluation will error out with a hint for the user to run `nix run .#resolve` first to generate the dream-lock.json.
Also for projects using pure translation, `nix run .#resolve` will still generate the `dream-lock.json` file to increase evaluation performance in the future.
Other changes:
- Add the capability of selecting the `translator` and `translatorArgs` …

Support impure translation via flakes (no more CLI)

---

flake.nix
src/apps/cli/commands/add.py
src/apps/cli/nix_ffi.py
src/default.nix

Push the nix configuration into the CLI so we don't need the overlay,
and so we don't need to create another instance of nixpkgs.
This also means that the python CLI can be executed directly as long as
the user has a recent-enough version of nix and make iterations a bit
faster.
For more details, see
https://zimbatm.com/notes/1000-instances-of-nixpkgs
TODO: the PR needs testing

use one nixpkgs instance

---

src/builders/rust/build-rust-package/default.nix
src/builders/rust/crane/default.nix
src/builders/rust/vendor.nix

This fixes some source replacement config issues that were happening with crane. It also makes behaviour more consistent across buildRustPackage and crane since now they both write configs to `CARGO_HOME`. The old behaviour was incorrect for `crane`, and so I have changed it to work for both. I chose to do it like this after reading [this comment](https://github.com/ipetkov/crane/blob/master/pkgs/configureCargoVendoredDepsHook.sh#L5-L10) from crane source.

fix(rust): fix source replacement config write for crane

---

src/builders/rust/build-rust-package/default.nix
src/builders/rust/crane/default.nix

Using hardcoded `/build` apparently causes some issues on darwin (?) (https://github.com/helix-editor/helix/pull/1758#issuecomment-1059903449). So this attempts to fix it by setting `CARGO_HOME` in a hook instead of hardcoding it in derivation.
~~Draft until it gets confirmed this actually fixes the issue. It doesn't seem to break anything for me (nix-cargo-integration tests pass fine) so it should be a welcome improvement anyways.~~ seems to fix that error!

fix(rust): dont use hardcoded CARGO_HOME to /build

---

src/translators/nodejs/pure/yarn-lock/default.nix

There's an edge case where a dependency in a yarn.lock file has a resolved address from `"package@git+https://..."`:
`git+https:...`
I am not sure why  `l.strings.sanitizeDerivationName` was commented out.
This is what fixed the issue for me.
Thanks @tomberek for the help & walkthrough.

fix: parse resolved keys with git+https correctly

---

flake.nix

I'd like to use dream2nix on an ARM64 machine. Passes `nix flake check`.

Add aarch64-linux support

---

src/translators/nodejs/pure/yarn-lock/default.nix

I was having the following error:
```
error: attribute 'packages/subpackage' missing
at /nix/store/89qhl4fvd5g806ja3dd3rsyrvj3qxyhw-source/src/utils/translator2.nix:159:15:
152|             children =
153|               depGraphWithFakeRoot."${node.name}"."${node.version}";
|               ^
154|
```
Here's a test `package.json`:
```
{
"name": "test2",
"version": "1.0.0",
"private": true,
"workspaces": {
"packages": [
"packages/subpackage"
]
},
"dependencies": {
"typescript": "^4.6.2"
}
}
```
and `packages/subpackage/package.json`:
```
{
"name": "some-name",
"version": "1.0.0",
"private": true,
"dependencies": {
"type-detect": "^4.0.8"
}
}
```
It appears `workspaceDependencies` always took the workspace's relative path instead of checking if the json has the name attribute first.

fix: use name attr before workspace path

---

src/default.nix
src/fetchers/default-fetcher.nix
src/translators/rust/pure/cargo-lock/default.nix
src/utils/translator2.nix
tests/examples/default.nix

Resolves #113. This uses `discoveredProjects` to find dependencies that are outside of the `inputDir` passed to the `cargo-lock` translator.
This also reworks how the `cargo-lock` translator finds Cargo packages. Since packages / workspaces discovery is handled by the discoverer now, that is replaced with just finding packages for workspace members if the translator is translating a workspace. This makes everything a lot simpler, and generally should make everything faster (no `recurseFiles`...).
It is currently a draft because there is a bug preventing this from fully working:
```
error: cannot coerce null to a string
at /nix/store/0ziix5kkds3rkqsjc48bzlnyf5a1y2kw-source/src/fetchers/default-fetcher.nix:30:38:
29|           then throw "source for ${name}@${version} is referencing itself" …
```

feat(translator/cargo-lock): use discoveredProjects to find dependencies that are outside of a packages source

---

overrides/nodejs/default.nix

7zip just doesn't build on darwin.
here is the failure
```
> automatically fixing dependencies for ELF files
> /nix/store/m7jxsbvwvkw2zdvlqqqqdbcvr14cp6an-auto-patchelf-hook/nix-support/setup-hook: line 333: -l: command not found
```
looking into the file here is what there is
```
segmentHeaders="$(LANG=C $READELF -l "$file")"
```
readelf doesn't seem to exist on darwin, so this step is probably not possible at all.

7zip fix darwin build

---

overrides/nodejs/default.nix

esbuild unfortunately has a version check when you run it.
I've managed to run it successfully today.
feel free to let me know if you don't like the approach

esbuild: remove version check

---

src/apps/cli/nix_ffi.py
src/default.nix
src/lib/simpleTranslate2.nix
src/templates/translators/impure.nix
src/templates/translators/pure.nix
src/translators/nodejs/pure/yarn-lock/default.nix
src/translators/rust/pure/cargo-lock/default.nix
tests/unit/default.nix
tests/unit/test_pure_translators.py

This PR should make it simpler for contributors to add and maintain translators.
Pure translators using `simpleTranslate2` can now enable unit tests by adding project sources to `generateUnitTestsForProjects`.
See updated translator template: https://github.com/nix-community/dream2nix/blob/31c258880cf0bb4cb7ef1597c2f8a1e7b53a1b2e/src/templates/translators/pure.nix
Unit test generation is already enabled for `yarn-lock` and `cargo-lock` translators.

Automatically generate unit tests for pure translators

---

overrides/nodejs/default.nix
src/builders/nodejs/granular/default.nix

I'm not sure how to disable it, but it looks like by default the evaluation on darwin is impure for electron.
the the resulting directory looks exactly right, and the only thing to do is change the electron wrapper.
Let me know if that works for you.
electron is working, just showing a `Electron could not be found. No hard resets for you!` warning before running

electron: fix darwin build

---

src/builders/rust/vendor.nix
src/translators/rust/pure/cargo-lock/default.nix

This fixes an issue with the `workspaceToml` that was found not being used, and instead the `nonWorkspaceToml` being used, which causes `getRoot` to return `null` for `pname` and `version` because `nonWorkspaceToml`s do not have roots.
EDIT: also added a small fix for path replacement accidentally replacing features

fix(translator/cargo-lock): prioritize workspaceToml for path dependencies

---

src/builders/rust/build-rust-package/default.nix
src/builders/rust/crane/default.nix
src/builders/rust/utils.nix
src/builders/rust/vendor.nix
src/default.nix
src/translators/rust/pure/cargo-lock/default.nix

- don't hardcode a path to `/build` in `buildRustPackage` (breaks builds on mac)
- vendor all dependencies in the Cargo.lock and use that in builds, this fixes issues with cargo complaining about unvendored dependencies (should fix #129)
- organize some code better

Another round of rust fixes

---

src/builders/rust/build-rust-package/default.nix

I have dream2nix complaining about missing `../.cargo/config` and I don't know if it's the right fix but it seems ok

don't mv ../.cargo/config if it doesn't exist

---

src/default.nix
src/translators/rust/pure/cargo-lock/default.nix

This also exposes `makeOutputsForDreamLock`, which i use on https://github.com/yusdacra/dream2nix-crates-io.

fix(translator/cargo-lock): fix some bugs regarding source entry parsing and getting checksums

---

src/translators/rust/pure/cargo-lock/default.nix

Fixes an issue with the `cargo-lock` translator. Apparently the tests didn't catch this. Should probably add a test with a crate that has git dependencies.

fix(translator/cargo-lock): dont assume parsed.type exists, use `or null`

---

src/fetchers/git/default.nix

Fixes an issue where the ref was being defaulted to empty string if it wasnt passed, which was causing the check to always fail.

fix(fetcher/git): handle ref checking correctly

---

src/translators/rust/pure/cargo-lock/default.nix

Adds a new test to the `cargo-lock` translator that has git dependencies.

tests: add cargo-lock translator test with git dependencies

---

src/translators/rust/pure/cargo-lock/default.nix

…because they are no longer needed.

refactor(translator/cargo-lock): dont add name and version to crates-io source

---

examples/path-example/flake.lock
examples/path-example/flake.nix
examples/path-example/package.json
examples/path-example/packages/cli/bin/cli.js
examples/path-example/packages/cli/package.json
examples/path-example/packages/lib/package.json
examples/path-example/packages/lib/src/main.js
src/default.nix
src/fetchers/default-fetcher.nix

Changes the built-in path fetcher to resolve relative paths relative to the source root, allowing to build packages from the same repository the lockfile resides in. A test package that doesn't build without those changes and starts building with them was added.

Resolve `path` sources relative to the source root

---

examples/path-example/flake.lock
examples/path-example/flake.nix
examples/path-example/package.json
examples/path-example/packages/cli/bin/cli.js
examples/path-example/packages/cli/package.json
examples/path-example/packages/lib/package.json
examples/path-example/packages/lib/src/main.js
src/discoverers/nodejs/default.nix
src/translators/nodejs/pure/package-lock/default.nix
src/translators/nodejs/pure/yarn-lock/default.nix
tests/examples/default.nix

Alternative fix to https://github.com/nix-community/dream2nix/pull/143
The problem here was that we changed the path source some time ago to expect a `rootName` and `rootVersion`. The package-lock and yarn-lock translators simply didn't set these values, which is fixed by this PR
@jaen @yusdacra

Path improvements

---

examples/no-cargo-lock-example/dream2nix-packages/rand/dream-lock.json
examples/no-cargo-lock-example/dream2nix-packages/rand/rand_distr/benches/dream-lock.json
examples/no-cargo-lock-example/flake.lock
examples/no-cargo-lock-example/flake.nix
src/builders/rust/build-rust-package/default.nix
src/builders/rust/crane/default.nix
src/builders/rust/utils.nix
src/discoverers/rust/default.nix
src/translators/default.nix
src/translators/rust/impure/cargo-toml/default.nix
src/translators/rust/pure/cargo-lock/default.nix

This implements a new impure `cargo-toml` translator that can translate Cargo projects that don't have a `Cargo.lock` file. In addition, it makes the `cargo-lock` translator not put absolute paths for fixing up path dependency paths in a `Cargo.toml`, instead relative paths are used now, because absolute paths break the generated dream-lock. Rust discoverer is also updated to support the new translator.
~~This is a draft because it doesn't seem to be able to build stuff properly (`ripgrep` doesn't build).~~ `ripgrep` builds fine now.

feat: implement cargo-toml impure translator for rust subsystem

---

src/default.nix

This makes a change to expose all builder outputs in `realizeProjects`.

fix: expose all builder outputs

---

README.md
examples/d2n-extended-new-subsystem/flake.nix
examples/d2n-extended/flake.nix
examples/d2n-init-pkgs/flake.lock
examples/d2n-init-pkgs/flake.nix
examples/eslint-aggreagted/flake.nix
examples/eslint/flake.nix
examples/mattermost-webapp/flake.nix
examples/no-cargo-lock-example/flake.nix
examples/path-example/flake.nix
examples/prettier/flake.nix
examples/ripgrep/flake.nix
src/default.nix
src/lib.nix
src/utils/default.nix
templates/simple/flake.nix
tests/examples/default.nix

This implements a `makeDream2nix` function for creating a dream2nix instance with `externalSources` and `externalPaths` already provided. This is useful because otherwise you have to create these yourself, and since this is a flake lib function it's more convenient than `import`ing the `src/default.nix` (`dream2nix.lib.makeDream2nix {inherit pkgs;}` as opposed to `import "${dream2nix}/src" {inherit pkgs;}`). It is also useful for users of dream2nix that don't want dream2nix to "take over" the flake outputs, but still want to take advantage of the flake.

feat: implement makeOutputs that outputs `system`less structure 

---

src/lib/default.nix
src/lib/discoverers.nix
src/lib/simpleTranslate2.nix
src/templates/builders/default.nix
src/templates/translators/impure.nix
src/templates/translators/pure.nix

This aims to reduce the complexity of adding support for new ecosystems to dream2nix.
Now`discoverProject` can be defined in a translator, which allows to detect projects for that translator with a simple 3-liner.
This should be the default, and only later if complexity is required a fully featured discoverer needs to be implemented.
This is achieved by generating a `defaultDiscoverer` in `./src/lib/discoverers.nix` which iterates over all the existing `discoverProject` definitions of all translators and traverses the source tree calling these functions on each directory.
Other fixes:
`dlib.callViaEnv` now re-creates contexts for store path passed via the JSON. This is important for the python-ffi. Before this, IFD based translators could not be unit tested because the string context got …

Simpler discover

---

src/default.nix
src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/builders/node2nix/default.nix
src/subsystems/python/builders/simple-builder/default.nix
src/subsystems/rust/builders/build-rust-package/default.nix
src/subsystems/rust/builders/crane/default.nix

Changes builder outputs so that they fit the new flake outputs schema (nix 2.7+). Current nixos stable nix version is 2.8, so this should be an OK change.

refactor: use new flake output schema for default package and devshells

---

flake.lock
flake.nix

Changes the devshell dream2nix uses from nixpkgs' mkShell to numtide's devshell. Reduces the amount of env vars exported by a lot and we can add commands and make them visible more easily, so it may be helpful in the future potentially.
Also changes from using `devShell` output to `devShells`, according to the new flake outputs since 2.7+.

chore: use numtide devshell instead of nixpkgs mkShell

---

docs/src/subsystems/rust.md
examples/set-rust-toolchain/flake.nix
src/default.nix
src/lib.nix
src/subsystems/rust/builders/build-rust-package/default.nix
src/subsystems/rust/builders/crane/default.nix
src/subsystems/rust/builders/utils.nix
src/utils/override.nix

This implements an override for the Rust builders called `overrideRustToolchain` that can be used to override the Rust toolchain packages used by the builders. This also enables regex overrides for packages so that overriding the toolchain globally is made much more convenient.

feat: implement overrideRustToolchain for crane and build-rust-package

---

src/subsystems/rust/builders/build-rust-package/default.nix
src/subsystems/rust/builders/crane/default.nix
src/subsystems/rust/builders/utils.nix

Adds devshells for the Rust builders outputs. This is pretty simple, as it is basically just the packages themselves but with the Rust toolchain added so `cargo` and `rustc` is available in the shell.

feat(rust): add devshells to rust builder outputs

---

overrides/nodejs/default.nix

This override fixes the build for ratel (the package I added to dreampkgs).
This is most probably not the override that makes puppeteer work, however it does complete the build.
I would say we merge this now and when we encounter a dependency that fails with a puppeteer related failure we update the override.

puppeteer: initial override

---

README.md
examples/eslint/flake.nix
src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/python/builders/simple-builder/default.nix

This adds `devShell` and `devShells` outputs to the python and nodejs default builders
That means, flake outputs generated by `makeFlakeOutputs` will be suitable for use with `nix develop` or `direnv`.

add devShell outputs for nodejs ad python

---

src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/builders/granular/fix-package.py
src/subsystems/nodejs/builders/granular/install-deps.py

- unsure that all executables of transitive dependencies are linked to /lib/node_modules/.bin
- stop adding many store paths to PATH, instead add .bin directory to PATH
- if installMethod=copy, .bin symlinks will now point to the local copy of the dependency instead of the original store path. This improves issues with runtime dependency errors in some situations

nodejs: improve builder (executable linking)

---

src/indexers/libraries-io/default.nix

Indexer which utilizes the libraries.io api.
Given a platform (like npm or crates-io), it returns a list of packages sorted
by the highest number of dependents
(the number of other packages which depend on that package).
This indexer requires an api key that must first be created on libraries.io.
Github login is supported, so this is very straight forward.
More options could be added.
libraries.io also supports other interesting popularity metrics:
- dependent_repos_count
- stars
- forks
- rank (source rank, see https://libraries.io/api#project-sourcerank)

indexer: add libraries-io

---

src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/builders/granular/devShell.nix

fixes #204 
Now top-level packages are built by default with `installMethod=copy` to prevent symlinking issues.
The shellHook now always overwrites existing ./node_modules with a full
flat copy of all transitive dependencies produced by dream2nix from
the lock file.
This allows good interop with npm. npm is still needed to update or
add dependencies. npm can write to the ./node_modules without
any issues and add or replace dependencies.
If npm modifies ./node_modules, then its contents will be a mix of
dream2nix installed packages and npm installed packages until the
devShell is re-entered and dream2nix overwrites the ./node_modules
with a fully reproducible copy again.

Nodejs devShell: improve & allow for good interop with npm

---

overrides/nodejs/default.nix

I wonder if there's no way to automatically generate this in the impure phase? The module now has a check for the binary version and doesn't like it when there's a mismatch.

nodejs: upgrade esbuild 0.14 override

---

docs/src/SUMMARY.md
docs/src/guides/getting-started-nodejs.md
docs/src/guides/getting-started-python.md
docs/src/install-nix.md

Currently there is only a python quickstart guide, which is very nice.
This PR will add a similar guide for nodejs.

docs: add nodejs quickstart guide

---

src/subsystems/haskell/translators/stack-lock/default.nix
src/subsystems/haskell/translators/stack-lock/utils.nix
src/subsystems/haskell/translators/utils.nix

Some things I'm not sure of:
1. Do we additionally want to use `all-cabal-json` for the top-level
file? This would have the drawback of yielding outdated data for a
developer of a Haskell project who wants to use `dream2nix` to
manage their project. I'm not sure if `dream2nix` is really
designed for that use though.
2. Do we want to continue using `all-cabal-hashes` in the `stack-lock`
translator? We end up copying a Cabal file from `all-cabal-hashes`
in the builder anyway. Though I'm not sure why we don't simply use
the Cabal file from the source tree.

translators/stack-lock: Use nix-community/all-cabal-json

---

src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/builders/granular/devShell.nix
src/subsystems/nodejs/builders/granular/install-deps.py

Fixes #221 
At the end of the `src/subsystems/nodejs/builders/granular/install-deps.py`, 
read `package.json`,
and link bins of direct dependencies to `node_modules/.bin`.
Needs to pass the `src` (+ run unpack phase) to `devShell` so `package.json` is available.

fix: nodejs: link direct bins

---

src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/builders/granular/fix-package.py
src/subsystems/nodejs/builders/granular/link-bins.py

Fixes #235 
Do not link bins from the `package.json` in the `d2nPatchPhase`, instead link in the `installPhase`.
Some of the binaries may have to be built (e.g. typescript compile).
Tested on [`serve`](https://github.com/vercel/serve):
```nix
{
inputs = {
dream2nix.url = "github:tinybeachthor/dream2nix/fix-nodejs-link-built-binary";
serveSrc = {
url = "github:vercel/serve/main";
flake = false;
};
};
outputs = { self, dream2nix, serveSrc }:
dream2nix.lib.makeFlakeOutputs {
systemsFromFile = ./nix_systems;
config.projectRoot = ./.;
source = serveSrc;
packageOverrides = {
serve = {
"compile" = {
buildScript = ''
npm run compile
'';
};
};
};
};
}
```

fix: nodejs: link package bins after buildPhase

---

docs/src/SUMMARY.md
docs/src/subsystems/node.md

Add a new section to subsystems describing the node.js translators/builders.

docs: add nodejs subsystems page

---

.github/workflows/tests.yml
flake.nix
tests/integration/default.nix
tests/integration/tests/.gitignore
tests/integration/tests/nodejs_built-binary/flake.nix
tests/integration/tests/nodejs_built-binary/package.json
tests/integration/tests/nodejs_direct-priority-over-transitive/flake.nix
tests/integration/tests/nodejs_direct-priority-over-transitive/package.json

Add integration tests to detect regressions for #221, #235.
Run tests in github action.

test: add integration tests

---

src/default.nix
src/lib.nix
src/lib/discoverers.nix
src/utils/default.nix

Aside from the automatically discovered project, this allows adding extra `projects` like in this example flake.nix.
```nix
{
inputs = {
dream2nix.url = "github:nix-community/dream2nix";
};
outputs = {
self,
dream2nix,
} @ inp: (dream2nix.lib.makeFlakeOutputs {
systems = ["x86_64-linux"];
config.projectRoot = ./.;
source = ./.;
projects = {
htop = {
name = "htop";
translator = "debian-binary";
};
};
});
}
```
Right now the source is still required. In the future we should make the `source` field optional.
@a-kenji Probably relevant for your debian translator

feat: allow passing project without source

---

.github/workflows/tests.yml
tests/examples/default.nix
tests/integration/default.nix

- run more jobs in parallel for `example` and `integration` tests
- use cachitx for unit tests

chore: CI performance improvements

---

docs/src/SUMMARY.md
docs/src/subsystems/php.md
src/subsystems/php/translators/composer-json/default.nix
src/subsystems/php/translators/composer-lock/default.nix
src/subsystems/php/utils.nix

Towards #240  
Found out a couple of issues with `composer-lock` translator (mostly semver resolution).

php: impure translator `composer-json` + fix `composer-lock`

---

src/apps/contribute/contribute.py

The stdout of `nix run .#contribute` was `The template has been initialized in ./src/subsystems//$lang/$module_type/$module_name/default.nix`.
There are two slashes after `subsystems`.

chore: apps contribute: remove a redundant slash

---

src/specifications/subsystems/nodejs/dream-lock-schema.json
src/specifications/subsystems/nodejs/dream.lock.example.json
src/specifications/subsystems/rust/dream-lock-schema.json
src/subsystems/nodejs/builders/granular/default.nix
src/subsystems/nodejs/translators/package-lock/default.nix
src/subsystems/nodejs/translators/yarn-lock/default.nix
src/utils/default.nix

- Create validation for existing schemas
- Validate only for subsystems with existing schemas
- Also add schemas for nodejs and rust
Co-authored-by: a-kenji <aks.kenji@protonmail.com>

Add schema validation for specific subsystems

---

src/subsystems/rust/builders/crane/default.nix
src/subsystems/rust/builders/vendor.nix

- vendoring only gets copied to dependencies derivation and from there it is propagated to the main derivation
- vendoring directory is copied recursively as symlinks to reduce the amount of data copied

fix(rust/crane): improve vendoring

---

docs/src/subsystems/php.md
examples/php_composer/flake.nix
src/lib/builders.nix
src/subsystems/php/builders/simple/default.nix
src/subsystems/php/builders/simple/devShell.nix
src/subsystems/php/discoverers/default/default.nix
src/subsystems/php/semver.nix
src/subsystems/php/translators/composer-json/default.nix
src/subsystems/php/translators/composer-lock/default.nix
src/subsystems/php/utils.nix

Towards #240 
Disable packagist.org repo for composer, use [artifact](https://getcomposer.org/doc/05-repositories.md#artifact) or path repositories.

php: builder

---

src/apps/translate/default.nix
src/subsystems/rust/translators/crates-io/default.nix

- feat: skip cargo-toml translator if a Cargo.lock already exists

feat: skip cargo-toml translator if a Cargo.lock exists on crates-io translator

---

src/subsystems/nodejs/discoverers/discoverer-nodejs/default.nix
src/subsystems/nodejs/translators/package-lock/default.nix
src/subsystems/nodejs/translators/utils.nix

[npm-shrinkwrap.json](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) is an alternative to package-lock.json that follows the same format. It is typically used with applications (rather than libraries) distributed via npm's registry. This change detects its presence and feeds it through the package-lock translator if it exists.
Per the npm documentation, npm-shrinkwrap.json takes precedence over package-lock.json.

nodejs: support npm-shrinkwrap.json for package-lock translator

---

examples/haskell_cabal-freeze/flake.nix
flake.lock
flake.nix
src/specifications/subsystems/haskell/dream.lock.example.json
src/subsystems/haskell/builders/simple-haskell/default.nix
src/subsystems/haskell/translators/cabal-freeze/default.nix
src/subsystems/haskell/translators/cabal-freeze/parser.nix
src/subsystems/haskell/translators/stack-lock/default.nix
src/subsystems/haskell/translators/utils.nix
tests/unit/default.nix

This is almost done, but I need some help to figure out how to remove IFD.
I am guessing that adding the `all-cabal-json` and `ghc-utils` repos as flake inputs would solve the issue, but I'm not sure how to do it cleanly; something like https://github.com/leungbk/dream2nix/commit/5cae258c0f80238173bb220ffb7d49446952d3c0 (not on this branch) might be too error-prone, plus I'm not sure if it's very clean to simply pass those two repos' sources as a default value of `inputs` to `src/default.nix` (which I haven't done; I think something like that would be necessary to make the tests pass). Assuming that works around IFD, is there a way of passing down those repos that is cleaner than drilling `inputs` all the way?

Add cabal-freeze support

---

src/subsystems/nodejs/builders/granular-nodejs/default.nix

This is currently just a small hack provided by @max-privatevoid on matrix that's worked as expected in several places.
A lot of problems come up when building using the granular builder in nodejs because the directory structure in dream2nix's outputs `$out/lib/node_modules/` is a bit different than what node module resolvers expect, causing the inability to find eachother.
Fixes:
https://github.com/nix-community/dream2nix/issues/237
https://github.com/nix-community/dream2nix/issues/303
Potentially fixes:
https://github.com/nix-community/dream2nix/issues/120
https://github.com/nix-community/dream2nix/issues/158
https://github.com/nix-community/dream2nix/issues/324

Fix: make sourceRoot emulate normal nodejs build

---

examples/_d2n-extend-devShell/flake.nix
examples/nodejs_prettier/flake.nix
src/default.nix
src/lib/default.nix

This introduces dlib.mergeFlakes, making at a bit easier to extend the dream2nix generated flake outputs with other flake outputs.
An example is added demonstrating how to extend a devShell generated by dream2nix.

Dev shell example

---

.github/workflows/tests.yml

Auth tokens are easier to rotate

ci: replace cachix signing key with auth token

---

docs/src/subsystems/rust.md
examples/_d2n-extended/flake.nix
examples/_d2n-flake-parts/flake.nix
examples/_d2n-init-pkgs/flake.nix
examples/rust_no-cargo-lock/flake.nix
examples/rust_set-rust-toolchain/flake.nix
overrides/rust/default.nix
src/subsystems/rust/builders/crane/default.nix

Introduces new env vars for crane builder:
- `cargoTestProfile` and `cargoBuildProfile` for setting the profile to be used when compiling
- `cargoTestFlags` and `cargoBuildFlags` for setting arbitrary flags
This is so that users can easily set flags and profile, like you can do already with `buildRustPackage` builder since that also uses env vars for these.
Also changes some of the projects used in Rust examples to reduce load on CI (we may also want to change other examples like the php composer example which seems to take a long time to build)

feat: make crane builder more easily configurable

---

examples/_d2n-define-projects-manually/flake.nix
src/default.nix
src/lib.nix
src/modules/flake-parts/implementation.nix
src/modules/functions.discoverers/implementation.nix

This change allows to take control over the project definition completely and not use discovery at all.
Here an example flake that builds prettier using the current PR:
```nix
{
inputs = {
dream2nix.url = "github:nix-community/dream2nix/ba44952315ea9aa11f45d80b563ffeea996e06bf";
nixpkgs.follows = "dream2nix/nixpkgs";
flake-parts.url = "github:hercules-ci/flake-parts";
src.url = "github:prettier/prettier/2.4.1";
src.flake = false;
};
outputs = {
self,
dream2nix,
flake-parts,
src,
...
}:
flake-parts.lib.mkFlake {inherit self;} {
systems = ["x86_64-linux"];
imports = [dream2nix.flakeModuleBeta];
perSystem = {config, ...}: {
dream2nix.inputs."prettier" = {
source = src;
projects = {
prettier = {
name = "prettier";
subsystem = "nodejs";
translator = "yarn-lock";
};
};
};
};
};
}
```

No discovery

---

docs/src/intro/override-system.md

Comprehensive examples and explain how the override system works
Currently only for the nodejs subsystem.
Maintainers of subsystems can/should currently add their attributes as well.
As i dont know when we're going to have an auto-gen-docs of those, it would be nice for people to know right away what attributes they can override.

docs: improve override section

---

src/subsystems/nodejs/builders/granular-nodejs/devShell.nix

The devShell in nodeJs subsystem creates broken symlinks (unrelated to my other current PRs)
fixes the following two problems:
- `../$target` is creating a relative link, but $target already hold an nix store path, which is absolute
- line `for link in $(ls ${binDir}); do` the `ls` command should not be used in shell `for...in` as here an additional `magic` file `->` appears because it tries to split the string that is also holding an -> from the ls command. e.g. `ls $binDir` returns `tsc -> nix/store/..../.bin/tsc` but that string gets splitted and it creates an file for ->

fix: nodejs devShell creates broken links

---

src/subsystems/nodejs/builders/granular-nodejs/devShell.nix

realpath resolves all links recursively where the executable for sure exists. 
Otherwise creating the devShell will fail.
readlink does only resolve one layer of links, which in some cases is not enough as if one link gets cleaned up after build it will break.
@Kazimazi this should resolve your recent problems.

replace readlink by realpath

---

examples/python_poetry/flake.nix
src/modules/flake-parts/implementation.nix
src/modules/flake-parts/interface.nix
src/modules/flake-parts/makeOutputsArgs.nix

Defines a module in `./src/modules/flake-parts/makeOutputsArgs.nix` , which defines an option for each argument that the `makeOutputs` function expects.
I've left TODO comments around the place where I'm not certain about things. 
Goes some way towards fixing #320

Leverage module system to type check and document `makeOutputs` arguments

---

examples/_d2n-init-pkgs/flake.nix
src/lib.nix

I'd like to reduce the API surface, so the overhead in maintaining backwards compatibility is lower.
Therefore I'd like to remove makeOutputs from the examples and not promote its use anymore.
The only example where it is used is the one for `importing nixpkgs manually`.
But there is no reason to use makeOutputs for this anyways. This can be done with makeFlakeOutputs as well and is even easier. There was just a [bug that I needed to fix](https://github.com/nix-community/dream2nix/commit/e4a682ba0e81b617b428fcb81983978a57010a53).
@yusdacra I saw that you are using `makeOutputs` in nix-cargo-integration. Would you be OK, with changing to makeFlakeOutputs? Then there would only one function for which we need to ensure backwards compatibility. Everything else becomes playground and future …

Remove makeOutputs from examples

---

src/specifications/dream-lock-example.json
src/specifications/dream-lock-schema.json

Fixes a typo introduced in 2a3582741947e6f6d3bff8344562327d43df7114 and adapts the schema to reflect changes.
@DavHau

fix dream-lock example & schema

---

src/subsystems/python/builders/simple-python/default.nix

This arg was inadvertently added to `pip install` in #397; it breaks transitive dependencies on the packages we custom-install, like setuptools and wheel.
Per @phaer, it wasn't supposed to be there and has already been removed in the next set of larger changes, but this should fix those transitive dependencies in the meantime.

fix: python: remove spurious --ignore-installed

---

src/lib.nix

Still allow the user to execute the `detect-projects` app

fix: makeFlakeOutputs: throw lazily when projects unspecified

---

docs/src/subsystems/rust.md
src/modules/builders/implementation.nix

Changes default Rust builder to crane since it's easier to work with and is good enough to have as default. Also has more benefits compared to `buildRustPackage`, so it's better to have this as default until we get a granular builder for Rust.

feat(rust): change default builder to crane

---

flake.nix
src/apps/replaceRootSources/replaceRootSources.py
src/apps/translate-index/summarize-stats.py
src/indexers/crates-io-simple/process-result.py
src/indexers/libraries-io/process-result.py
src/indexers/npm/process-result.py
src/modules/utils.index/build-script.py
src/modules/utils.index/make-stats.py
src/modules/utils/cli/aggregate-hashes.py
src/modules/utils/cli/format-dream-lock.py
src/modules/utils/cli/nix_ffi.py
src/subsystems/debian/translators/debian-binary/generate_dream_lock.py
src/subsystems/haskell/translators/hackage/fixup-dream-lock.py
src/subsystems/nodejs/builders/granular-nodejs/fix-package.py
src/subsystems/nodejs/builders/granular-nodejs/install-deps.py
src/subsystems/nodejs/builders/granular-nodejs/link-bins.py
src/subsystems/nodejs/translators/npm/fixup-dream-lock.py
src/subsystems/python/translators/pip/generate-dream-lock.py
tests/unit/test_dream_lock.py
tests/unit/test_pure_translators.py
tests/unit/test_source_shortcuts.py
tests/unit/test_utils.py
treefmt.toml

Integrate python formating to treefmt.
via [d98d3ef](https://github.com/nix-community/dream2nix/commit/d98d3efb4a315ce3db3aa513f90e51c54e544254) 
Files to Review:
- flake.nix
- treefmt.toml
All other files in this commit are formatted by black.
I suggest merging this before any other PRs getting merges because it may cause conflicts.

chore: add formatting of python

---

src/subsystems/racket/builders/simple-racket/default.nix
src/subsystems/racket/builders/simple-racket/make-new-config.rkt

The PLTADDONDIR contains [user-specific Racket configuration](https://docs.racket-lang.org/reference/Filesystem.html#%28idx._%28gentag._356._%28lib._scribblings%2Freference%2Freference..scrbl%29%29%29).
For example, is used by `raco` to install and locate a user’s `raco-commands`.
For the current builder, it defaults to the user’s home directory `$TMP_RACO_HOME`. The built `raco` binary, however, defaults to the homeless shelter. This means that the built `raco` can't locate any `raco-commands` in packages installed by the builder.
This commit creates a `PLTADDONDIR` directory structure in `etc` and sets it as an environment variable to all binaries. The paths in `config.rkdt` also point to this directory structure.
There might be a better way to address this - if so, please feel free to …

Add PLTADDONDIR environment variable to racket binaries.

---

src/subsystems/haskell/builders/simple-haskell/default.nix

This is one solution for #437.
We add a constraint to `configureFlags` for each dependency with the version specified in our dream-lock.
This fixes the issue, but it's a bit hacky. I don't know enough about the haskell toolchain to know whether there's a better solution.
This will probably at least be a good stop-gap until there's a better solution.

haskell builder: add a `--constraint` to `configureFlags` for each dependency

---

src/modules/flake-parts/makeOutputsArgs.nix

This might have been overlooked. The hackage haskell translator requires this option, but it's impossible to set using the flake-parts module.
This PR makes the option available.

flake-parts: add `version` option to the `project` submodule

---

overrides/haskell/default.nix

Add `pkgs.zlib` to haskell's `zlib` `buildInputs`.

haskell: add zlib override

---

examples/_d2n-flake-parts/flake.nix
examples/python_pip-freeze/flake.nix
examples/python_poetry/flake.nix
src/modules/flake-parts/makeOutputsArgs.nix

TL;DR it makes [this](https://github.com/nix-community/dream2nix/blob/9f6911c78dcb0832f7fcc955e847db1a5a9ce29a/examples/_d2n-flake-parts/flake.nix#L27) line unnecessary.

flake-parts: set default project name based on attribute name

---

docs/src/subsystems/rust.md
src/subsystems/rust/builders/crane/default.nix

This is useful for creating a devshell (when using crane) that includes `rustc` so rust-analyzer works properly.

rust: add rustc to crane's defaultToolchain and to crane devshell

---

src/subsystems/rust/builders/patch-workspace-deps.jq
src/subsystems/rust/builders/vendor.nix

This fixes issues like https://github.com/rust-lang/cargo/issues/11192 occurring in dream2nix Rust builders.

fix(rust): normalize dependencies inherited from workspace

---

src/specifications/subsystems/python/dream-lock-schema.json
src/subsystems/python/builders/simple-python/default.nix
src/subsystems/python/translators/poetry/default.nix

This is a continuation of my work in #397. It adds rather naive support for a subsystem attr `buildRequirements` in the translator.
This means we can install those `buildRequirements` during `buildPhase` instead of hard-coding packages like `poetry-core` in `buildInputs`. That approach didn't work for packages that explicitly require another version of `poetry-core` than what's in nixpkgs, as `buildPhase` would try and fail to uninstall the nixpkgs version before installing the required version.
It's naive in the sense that it leaves version constraints and platform compatibility tags ("markers") to pip. Which might or might not be a good idea for `buildRequirements`. 
[X] actually install the built wheel
[X] make sure buildRequirements don't leak into the final derivation or use …

Poetry: support build requirements

---

examples/haskell_cabal/flake.nix
examples/haskell_cabal/projects.toml
src/subsystems/haskell/translators/cabal/default.nix
src/subsystems/haskell/translators/cabal/fixup-dream-lock.py

The translator proposed here is basically an "impure wrapper" for the cabal-plan translator. It's a more general version of the hackage translator--all that's changed is that the source is pulled from the `source` option, instead of being downloaded from hackage using `name` and `version`.
The translator copies the source into a temporary directory, runs `cabal freeze`, runs the cabal-plan translator, and then patches in the original source (just like the hackage translator).

haskell: add impure cabal-plan translator based on hackage translator

---

docs/src/SUMMARY.md
docs/src/v1-api/consuming/inspect-options.md
docs/src/v1-api/consuming/override.md
docs/src/v1-api/integrating/integrate-lang2nix-impure.md
docs/src/v1-api/integrating/integrate-lang2nix-pure.md
docs/src/v1-api/packaging/monorepo.md
docs/src/v1-api/packaging/nodejs-init-project.md
docs/src/v1-api/packaging/nodejs-multiple-repos.md
docs/src/v1-api/packaging/nodejs-workspaces.md
docs/src/v1-api/problems.md
docs/src/v1-api/summary.md
docs/src/v1-api/users.md

v1 API does not exist yet.
I want to make sure that all relevant use cases are sketched out before starting with the implementation.

feat(v1 API): document v1 API examples

---

overrides/nodejs/default.nix

Hi, I'm adding a couple hashes for nodejs/electron override.
- 22.1.0: https://github.com/NixOS/nixpkgs/pull/213299
- 22.2.1: Missing (I personally need this lol)

chore: nodejs: add hashes for electron 22.1.0 and 22.2.1

---

examples/_d2n-flake-parts/flake.nix
src/modules/flake-parts/implementation.nix
src/modules/flake-parts/makeOutputsArgs.nix
tests/integration/tests/contribute/my-flake.nix

This PR does 2 things:
- Adds an optional `builder` option to the flake-parts module to match the standard dream2nix interface
- Removes the module's behavior of automatically exposing all packages in the `perSystem.packages` set (same for devShells)
- The previous logic was too strict as it resulted in running the entire translator logic just to evaluate `attrNames packages.${system}`. This is particularly problematic for larger flakes, where dream2nix and other packages are exposed together.

flake-parts: add builder option + don't expose packages automatically

---

src/subsystems/haskell/translators/cabal/fixup-dream-lock.py
src/subsystems/nodejs/builders/strict-builder/python-builder/app/lib/node_modules.py

Fixes #471 
Resolves edge-cases where the "package.json" file is not created yet in the directory but its nested node_modules are already created. Thus it creates a conflict, when trying to install the node_modules again.
Emits an Info into the logs just in case we need to further inspect this in the future.
@irisjae can you test if that works for your test case. Your project didnt provide any examples i could test other than building all dependencies.

nodejs: fix symlink issues

---

overrides/nodejs/default.nix

Subj, this patch appends NODE_PATH to the `moduleDirectories`
which according to [plugin docs][module-directories] would be used to
recursively search for modules.
It does, however, cause rollup to fail with an error, complaining
about absolute paths belonging in the [`modulePaths`][module-paths].
One way to work around this issue would be to split `moduleDirectories`
configuration across two lines, which would cause search and replace
to fail and subsequently rollup would not complain.
This workaround leads to working build, which leads me to believe that
existing comment is right and this patch is not needed in the first
place.
[module-directories]: <https://github.com/rollup/plugins/tree/master/packages/node-resolve#moduledirectories>
[module-paths]: …

fix: remove rollup patch

---

src/subsystems/php/translators/composer-lock/default.nix

It looks like `rootName` should be set to the *parent* name, but currently points at the name of the dependency component.
Fixes #488, though it seems this was changed intentionally by @tinybeachthor in #311 (specifically 156d7e0f50d37127d1aa5dae1cdc316aabe7eb2e), so this might break something else?

PHP: don't set rootName for `dist` type `path`

---

src/subsystems/python/builders/simple-python/default.nix

I encountered the following error when running `nix develop`
```
> Cannot copy . to .: destination already exists!
> Did you specify two "srcs" with the same "name"?
> do not know how to unpack source archive .
For full logs, run 'nix log /nix/store/fy1mpipp9xb7ds1m081q5x7f3c53j8i2-python3.10-default.drv'.
```
The error can be fixed with this PR. See https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-mkShell-usage

Fix error when src is a local directory in pip-freeze

---

.github/workflows/tests.yml
flake.lock
v1/nix/modules/drv-parts/fetch-pip/default.nix
v1/nix/modules/drv-parts/fetch-pip/interface.nix
v1/nix/modules/drv-parts/lock/default.nix
v1/nix/modules/drv-parts/lock/interface.nix
v1/nix/modules/drv-parts/mach-nix-xs/default.nix
v1/nix/modules/drv-parts/mach-nix-xs/interface.nix
v1/nix/modules/drvs/ansible/default.nix
v1/nix/modules/drvs/ansible/lock-x86_64-linux.json
v1/nix/modules/drvs/apache-airflow/default.nix
v1/nix/modules/drvs/apache-airflow/lock-x86_64-linux.json
v1/nix/modules/drvs/odoo/default.nix
v1/nix/modules/drvs/odoo/lock-x86_64-linux.json
v1/nix/modules/drvs/pillow/default.nix
v1/nix/modules/drvs/pillow/lock-x86_64-linux.json
v1/nix/modules/drvs/tensorflow/default.nix
v1/nix/modules/drvs/tensorflow/lock-x86_64-linux.json
v1/nix/modules/flake-parts/apps.update-caches.nix
v1/nix/modules/flake-parts/apps.update-locks.nix
v1/nix/modules/flake-parts/packages.nix
v1/nix/pkgs/fetchPip/fetchPip.nix

- adds module `fetch-pip`
- use fetch-pip for mach-nix.pythonSources + set defaults 
- make all packages use the module for pythonSources
- re-export all packages 
- add script .#update-locks that updates the lock files for all packages
@phaer

v1: manage all FOD hashes via `.#update-locks`

---

src/specifications/dream-lock-schema.json
src/subsystems/rust/builders/utils.nix
src/subsystems/rust/builders/vendor.nix
src/subsystems/rust/translators/cargo-lock/default.nix

fixes issues when duplicate dependencies are encountered
errors out in vendoring phase if duplicate versions are encountered (cargo vendor still does not support this behaviour)

feat(rust): prepare for duplicate dependency vendoring

---

src/subsystems/php/builders/granular-php/default.nix
src/subsystems/php/builders/simple-php/default.nix

Perform the patching in `postPatch` instead.
The advantage is that this means the original `patchPhase` becomes available again, so people can use `patches` in overrides. They can also still override `postPatch` if they want, and invoke the 'original' `postPatch` if they also want to keep the php builders' behavior.

PHP: don't override patchPhase

---

docs/src/intro/override-system.md
tests/integration-d2n-flakes/tests/php_transitive_with_target_dir/composer.json
tests/integration-d2n-flakes/tests/php_transitive_with_target_dir/composer.lock
tests/integration-d2n-flakes/tests/php_transitive_with_target_dir/flake.nix
tests/integration-d2n-flakes/tests/php_transitive_with_target_dir/projects.toml
tests/integration-d2n-flakes/tests/php_transitive_with_target_dir/test.php

Fixes #491 by documenting how to use flake `packageOverrides` to drop the attribute

Document how to drop PHP target-dir attribute

---

src/modules/flake-parts/makeOutputsArgs.nix

The error when you tried to use inject with the flake-parts module:
```
error: A definition for option `perSystem.x86_64-linux.dream2nix.inputs.self.inject.project' is not of type `list of list of string'. Definition values:
- In `/nix/store/lddrm4gcfbm2qbk4s5raahkii02xbb62-source/flake.nix, via option perSystem':
{
"0.0.1" = [
"@nestjs/mapped-types"
"1.2.2"
];
```

Fix: flake-parts: type check on inject

---

flake.lock
flake.nix
src/modules/externals/implementation.nix

This updates crane and its bindings and pins it to the current release.

crane: 0.10.0 -> 0.12.1

---

v1/nix/modules/drv-parts/pip/default.nix
v1/nix/modules/drv-parts/pip/interface.nix
v1/nix/modules/drvs/ansible/lock-x86_64-linux.json
v1/nix/modules/drvs/apache-airflow/lock-x86_64-linux.json
v1/nix/modules/drvs/odoo/lock-x86_64-linux.json
v1/nix/modules/drvs/pillow/lock-x86_64-linux.json
v1/nix/pkgs/fetchPipMetadata/src/fetch_pip_metadata/__init__.py
v1/nix/pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py

Introduce targets to lock. targets correspond to a set of python extra markers, e.g. "dev"
or "docs". We now write separate dependency trees for each requested
extra to the lock file.
We can then select a subset of those features using the new
"pip.buildExtras" option. Note that this option currently affects the
dependency tree only.
This approach is still not bullet proof, i.e. in cases where a
constraint of a package in "dev" changes the version of a package
in "default" during resolving.

v1/pip: support building with a subset of locked extras

---

src/modules/flake-parts/makeOutputsArgs.nix

This PR fixes the type specification of the `sourceOverrides` option to match the example and implementation, and add a line in the description to instruct users to look up the relevant version in `dream-lock.json`.

sourceOverrides: fix types and add documentation about the version

---

v1/nix/modules/drv-parts/buildPythonPackage/interface.nix
v1/nix/modules/drv-parts/lock/default.nix

Before this commit, the error messages for missing or outdated lock files read rather dense, compared to the stack trace above.

Some whitespace for lock file error formatting

---

v1/nix/modules/drvs/prettier-devshell/default.nix

Fixes a broken test surfaced via https://github.com/nix-community/dream2nix/pull/565

examples(nodejs): allow prettier-devshell derivation to be built

---

flake.nix
v1/nix/modules/drvs/apache-airflow/lock-x86_64-linux.json
v1/nix/modules/drvs/isso/lock-x86_64-linux.json
v1/nix/modules/flake-parts/packages.fetchPipMetadata.nix
v1/nix/pkgs/fetchPipMetadata/fetchPipMetadata.nix
v1/nix/pkgs/fetchPipMetadata/package.nix
v1/nix/pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
v1/nix/pkgs/fetchPipMetadata/src/pyproject.toml
v1/nix/pkgs/fetchPipMetadata/src/shell.nix
v1/nix/pkgs/fetchPipMetadata/src/tests/conftest.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_evaluate_extras.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_evaluate_requirements.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_git_repo_root.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_lock_entry_from_report_entry.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_lock_file_from_report.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_lock_info_from_fod.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_lock_info_from_path.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_path_from_file_url.py
v1/nix/pkgs/fetchPipMetadata/src/tests/test_repo_root.py

based on https://github.com/nix-community/dream2nix/pull/567
- fix(v1/pip): bug in fetchPipMetadata when multiple roots are requested
- chore: update lock files
This fixes the broken packages revealed by https://github.com/nix-community/dream2nix/pull/565:
- `apache-airflow`
- `isso`

fix(v1/pip): be able to deal with multiple root requirements

---

ci.nix

This reveals that some packages in `v1/nix/modules/drvs` are currently broken.

ci: enable hercules

---

modules/flake-parts/modules.drv-parts.core.nix
modules/flake-parts/packages.nix

This already includes the `lock` module and makes it easier to call dream2nix via evalModules

feat: add dream2nix.modules.drv-parts.core

---

src/subsystems/racket/builders/simple-racket/default.nix

Fixes https://github.com/nix-community/dream2nix/issues/527. 
I'm still figuring out how to move this change over to the new API.

Racket: Add binaries to $out/bin.

---

docs/src/SUMMARY.md

... but keep the md files. There are still valuable drafts which are not yet implemented

docs: remove v1 draft API docs from index

---

examples/dream2nix-packages-python/pyproject-dependencies/default.nix
examples/dream2nix-packages-python/pyproject-dependencies/my_tool/__init__.py
examples/dream2nix-packages-python/pyproject-dependencies/pyproject.toml
flake.lock
flake.nix
locks/example-package-python-pyproject-dependencies/lock-x86_64-linux.json
modules/drv-parts/pip-hotfixes/default.nix
modules/drv-parts/pip-hotfixes/interface.nix
modules/drv-parts/pip/default.nix
modules/drv-parts/pip/interface.nix
modules/flake-parts/checks.nix-unit.nix
modules/flake-parts/lib.evalModules.nix
pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
pkgs/fetchPipMetadata/src/shell.nix
pkgs/fetchPipMetadata/src/tests/test_evaluate_requirements.py
tests/nix-unit/test_pip_pyproject/default.nix

- adds new option flattenDependnecies (bool), to allow for dependency specifications without root (like a requirements.txt file).
- raise an informative error if flattenedDependencies is used the wrong way (like when it's set but a root with the current package name actually exists)
- adds new option ignoredDependencies to ignore dependencies. It cotains `wheel` by default, as building wheel using buildPythonPackage usually crashes due to conflicts
- pins the packaging library used to parse pip's report to the exact version that pip uses by refering to `pip._internal`
- prevents crashes when there is a cycle in the report -> instead remove the cycle
Other stuff:
- fix lib.evalModules
- fix devshell for the pip module python stuff

Python: fixes and improvements

---

modules/dream2nix/pip/default.nix

This prevents an error where mkDerivation.src is coerced to a string while it is null which leads to hard to debug scenarios
I don't think we need this default logic for the top-level. The logic is still kept for the dependencies.

fix(pip): remove default for `format`

---

examples/packages/multi-language/python-nodejs/default.nix
examples/packages/single-language/nodejs-no-lock/default.nix
examples/packages/single-language/nodejs-prettier-devshell/default.nix
examples/packages/single-language/nodejs-prettier-node-modules/default.nix
examples/packages/single-language/nodejs-prettier/default.nix
examples/packages/single-language/python-ansible/default.nix
examples/packages/single-language/python-apache-airflow/default.nix
examples/packages/single-language/python-odoo/default.nix
examples/packages/single-language/python-pillow/default.nix
examples/packages/single-language/python-pyproject-dependencies/default.nix
examples/packages/single-language/rust-ripgrep/default.nix
examples/packages/single-language/rust-workspace-version-inheritance/default.nix

Having this in the examples might confuse people

examples: remove use of `l = builtins // lib`

---

examples/packages/single-language/python-package-apache-airflow/default.nix
examples/packages/single-language/python-package-odoo/default.nix
modules/dream2nix/nixpkgs-overrides/interface.nix
modules/dream2nix/pip/default.nix

- nixpkgs-overrides are not lazy enough. They can lead to eval failures thrown in nixpkgs despite not being enabled. Therefore we better use the `import` as an enable mechanism instead of the `enable` option.
We keep the enable option to allow for users to disable the override module via mkForce

fix(pip): change nixpkgs-overrides & remove default for top-level source

---

pkgs/fetchPipMetadata/package.nix

When you had a pip git requirement such as `git+https://github.com/OCA/maintainer-tools`, `fetch_pip_metadata` was failing with:
```
Traceback (most recent call last):
File "/nix/store/v28wx7mr5m9wasbnmsij4dqfrgl0d28q-python3.10-fetch_pip_metadata/bin/.fetch_pip_metadata-wrapped", line 9, in <module>
sys.exit(fetch_pip_metadata())
File "/nix/store/v28wx7mr5m9wasbnmsij4dqfrgl0d28q-python3.10-fetch_pip_metadata/lib/python3.10/site-packages/fetch_pip_metadata/__init__.py", line 126, in fetch_pip_metadata
lock = lock_file_from_report(report, project_root=args.project_root)
File "/nix/store/v28wx7mr5m9wasbnmsij4dqfrgl0d28q-python3.10-fetch_pip_metadata/lib/python3.10/site-packages/fetch_pip_metadata/lock_file_from_report.py", line 240, in lock_file_from_report
name, package = …
```

fix: allow locking git dependencies with pip

---

modules/dream2nix/core/ui/default.nix

This allows updating the lock file via `nix run .#{package}.lock` instead of ` nix run .#{package}.config.lock.refresh`
This is better as it's shorter, and the keyword `lock` is widely understood to lock dependencies.

feat(ui): add .lock attribute

---

modules/dream2nix/core/ui/default.nix
modules/dream2nix/core/ui/interface.nix

This allows building evaluated dream2nix modules directly via the nix CLI without having to reference `.public`

feat(ui): add .drvPath top-level attribute

---

modules/dream2nix/pip/default.nix

Stripping is slow on large binary wheels and doesn't provide much benefit as it seems
It also prevents some breakages that can occur after stripping.

fix(pip): set dontStrip for all dependencies

---

modules/dream2nix/core/lock/default.nix

The suggested copy paste attribute path is often wrong as it depends on the individual repository setup that dream2nix doesn't control.
Instead now simply hint to `nix run` the .lock attribute

fix(lock): remove flakes command from error

---

examples/packages/single-language/python-project/default.nix

Use `lib.importTOML`, clearer than the previous implementation.
Reuse more information from `pyproject`.

docs: simplify python project example

---

modules/flake-parts/lib.nix

Before this patch, if a user calls `importPackages` and includes custom modules in the call, those would be lost.
@moduon MT-1075

fix: forward incoming modules when using `importPackages` interface

---

modules/dream2nix/pip/default.nix

In case you're building a python environment instead of a package, this output is very handy.

feat: output pyEnv for pip derivations

---

modules/dream2nix/pip/default.nix
modules/dream2nix/pip/interface.nix

Follow-up of https://github.com/nix-community/dream2nix/pull/676#discussion_r1326998054, now dependencies marked as buildInputs won't be included as propagatedBuildInputs for python derivations.

feat: allow to split buildInputs in python derivations

---

.gitignore
examples/packages/single-language/python-local-dependencies/default.nix
examples/packages/single-language/python-local-dependencies/lock.json
examples/packages/single-language/python-local-dependencies/subpkg1/pyproject.toml
examples/packages/single-language/python-local-dependencies/subpkg1/subpkg1.py
examples/packages/single-language/python-local-dependencies/subpkg2/pyproject.toml
examples/packages/single-language/python-local-dependencies/subpkg2/subpkg2.py
modules/dream2nix/pip/default.nix
pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
pkgs/fetchPipMetadata/src/tests/test_lock_info_from_path.py

The pip locker [sometimes created a URL without hash][1] to reflect that there was a local source.
This produced the following error when trying to evaluate that derivation:
… from call site
at /nix/store/qdzdi6qvrqxfqxhi3j70d5dsl9f5jpby-source/modules/dream2nix/pip/default.nix:86:28:
85|       mkDerivation = {
86|         src = l.mkDefault (fetchers.${metadata.sources.${config.name}.type} metadata.sources.${config.name});
|                            ^
87|         doCheck = l.mkDefault false;
… while calling 'url'
at /nix/store/qdzdi6qvrqxfqxhi3j70d5dsl9f5jpby-source/modules/dream2nix/pip/default.nix:57:11:
56|   fetchers = {
57|     url = info: l.fetchurl {inherit (info) url sha256;};
|           ^
58|     git = info: config.deps.fetchgit {inherit (info) url sha256 rev;};
error: value …

fix: improve handling of local python dependencies

---

modules/dream2nix/WIP-spago/default.nix

@DavHau I picked this up again and realized that recreating the lockfile then the build failed because now [package-set](https://github.com/purescript/package-sets/) is too new (we were always fetching `master`).
Unfortunately that repo doesn't have tags that includes package set versions (like `42.1.0`) so now the entire repo is fetched instead of the tarball and then I checkout the correct branch which is discovered checking commit messages.
There could be better ways but I believe it's enough for the lock script.

Fix spago lock script

---

modules/dream2nix/groups/group.nix
modules/dream2nix/groups/interface.nix
modules/dream2nix/groups/submoduleWithNameVersion.nix
tests/nix-unit/fixtures.nix
tests/nix-unit/test_groups/default.nix

implement options:
- `options.overrides`
- `options.groups.<name>.overrides`
Having this, it should not be necessary anymore to override members of a group directly. Instead the logic can be bound to package names, either globally for all groups, or locally for a single group.
We should probably also rename :
- `options.commonModule` -> `options.overrideAll`
- `options.groups.<name>.commonModules` -> `options.groups.<name>.overrideAll`

groups: implement global and local overrides

---

examples/packages/single-language/nodejs-project/default.nix
modules/dream2nix/nodejs-package-json-v3/default.nix
modules/dream2nix/nodejs-package-json-v3/interface.nix

- revert recent changes on nodejs-package-json
- instead introduce nodejs-package-json-v3
This way, existing users won't face breakages in the api

nodejs: fix backward compat for nodejs-package-json

---

modules/dream2nix/nodejs-devshell/tests/packages/basic/default.nix
modules/dream2nix/nodejs-devshell/tests/packages/basic/package-lock.json
modules/dream2nix/nodejs-devshell/tests/packages/basic/package.json
modules/dream2nix/nodejs-node-modules/tests/packages/basic/default.nix
modules/dream2nix/nodejs-node-modules/tests/packages/basic/package-lock.json
modules/dream2nix/nodejs-node-modules/tests/packages/basic/package.json
modules/dream2nix/nodejs-package-json/tests/packages/basic/app.ts
modules/dream2nix/nodejs-package-json/tests/packages/basic/default.nix
modules/dream2nix/nodejs-package-json/tests/packages/basic/lock.json
modules/dream2nix/nodejs-package-json/tests/packages/basic/package.json
modules/flake-parts/checks.nix

So far, /examples was the only place with packages that are built in the CI pipeline.
This change allows us to add package build tests to individual modules at the location where the module is defined. This has several benefits:
- We are not forced to add unnecessary examples in order to maintain test coverage
- When modules get removed, their tests will be removed alongside
- It allows us to keep old modules around and assure they keep working without having to keep outdated examples in /examples

test: add per module testing infra

---

pkgs/fetchPipMetadata/filter-pypi-responses.py

The pypi proxy filters packages, which can end up corrupting the pip cache. For an example of what this would look like, see https://github.com/pypi/warehouse/issues/14457

pip: disable cache for modified response

---

modules/dream2nix/nixpkgs-overrides/default.nix

Now that mkDerivation also has an `env` flag, we need to make sure to not forward this to mkDerivation, as we have our own env option.

nixpkgs-overrides: map env field correctly

---

modules/dream2nix/nodejs-package-json-v3/default.nix
modules/dream2nix/nodejs-package-json/default.nix
modules/dream2nix/nodejs-package-lock-v3/default.nix

Testing with pisignage-server, I found that it failed to create `lock.json` when I ran `flake run .#pisignage-server.lock`, presumably because https://github.com/colloqi/pisignage-server/blob/59d9fb6b238c00a2ba6d166cd58c444f738416bf/package-lock.json#L3108C4-L3108C4 requires git to fetch.
With this change, it now creates a `lock.json` - however without an `integrity` section:
```
"node_modules/919.socket.io": {
"version": "0.9.19",
"resolved": "git+ssh://git@github.com/colloqi/socket.io.git#7534db0e49b8310047527cc46e3c3342d3986be3",
"dependencies": {
"base64id": "0.1.0",
"policyfile": "0.0.4",
"socket.io-client": "0.9.16"
},
"engines": {
"node": ">= 0.4.0"
},
"optionalDependencies": {
"redis": "0.7.3"
}
},
```
... and even if it would have an `integrity` field, it fails to download:
``` …
```

Add git to the npm lock fetch script path

---

modules/dream2nix/pip/default.nix

This should resolve collision issues with the setuptools that gets propagated by setuptoolsBuildHook

pip: switch to format = "pyproject"

---

modules/dream2nix/WIP-python-pdm/default.nix
modules/dream2nix/core/paths/default.nix

This is the upstream default, so it doesn't hut to just include it everywhere

pdm: default to setuptools as build system

---

modules/dream2nix/WIP-python-pdm/default.nix

Without this, one easily runs into conflicts when creating overrides in downstream packages.
```
error: The option `groups.dev.packages.lxml."4.9.2".evaluated.deps.python' is defined multiple times while it's expected to be unique.
Definition values:
- In `/nix/store/37qh8mqrk809zmqcyfn86snqmf1p9j2d-source/modules/dream2nix/WIP-python-pdm, via option overrideAll': <derivation python3-3.11.6>
- In `/nix/store/xhpcrfk2h8wvy5jpvxi4rqhj9ffc9mfs-source/nix/drvs/my-package, via option overrideAll': <derivation python3-3.10.13>
```

pdm: only default to given python3 in overrideAll.

---

modules/dream2nix/core/lock/interface.nix

**Problem**: The default is an empty string but this violates the type constraint for the value which expects a list.
**Fix**: change empty string to empty array.
This bug is mentioned by @yukkop in this issue https://github.com/nix-community/dream2nix/issues/829

Fix type error in default value provided for option lock.extraScripts

---

modules/dream2nix/core/lock/default.nix

This allows running impure commands, that rely on user's configuration. E.g. to access a private gitlab project.

lock: Extend environment instead of replacing it

---

modules/dream2nix/nodejs-package-json-v3/default.nix

Fixes this bug:
```shell
➤ nix run gitlab:moduon/precommix/87d94a95c17d0aa3ac61d6e9d190221c0634c972#eslint.lock -L
error:
… while calling the 'head' builtin
at /nix/store/0zqp13i2jys5amxmyfxjr6kj62m7ncya-source/lib/attrsets.nix:922:11:
921|         || pred here (elemAt values 1) (head values) then
922|           head values
|           ^
923|         else
… while evaluating the attribute 'optionalValue.value'
at /nix/store/0zqp13i2jys5amxmyfxjr6kj62m7ncya-source/lib/modules.nix:854:5:
853|
854|     optionalValue =
|     ^
855|       if isDefined then { value = mergedValue; }
(stack trace truncated; use '--show-trace' to show the full trace)
error: The option `deps.writeScriptBin' is defined multiple times while it's expected to be unique.
Definition values:
- In …
```

fix(nodejs-package-json-v3): remove duplicate dependency

---

modules/dream2nix/WIP-python-pdm/default.nix
modules/dream2nix/core/paths/default.nix

- default to correct version of setuptools from lock file
- better default for python3 set in dream2nix.core.paths

pdm: fix various bugs

---

dev-flake/flake-compat.nix
lib/internal/fetchers/git/default.nix
modules/dream2nix/WIP-spago/default.nix
modules/dream2nix/nodejs-package-lock-v3/default.nix

This should lead to better performance
Also set allRefs=true in some places, as this reduces the risk of running into issues with older nix versions

fetching: set shallow=true for all fetchGit calls

---

examples/packages/basics/htop-with-flags/default.nix
examples/packages/basics/mkDerivation/default.nix
modules/dream2nix/core/default.nix
modules/dream2nix/core/eval-cache/interface.nix
modules/dream2nix/package-func/interface.nix
modules/flake-parts/apps.update-locks.nix

- don't import eval-cache and flags modules by default (those have never been used so far)
- mark options of package-func as internal. Those are for maintainers only and don't need to be rendered by default

cleanup core options

---

modules/dream2nix/WIP-python-pdm/default.nix
modules/flake-parts/website/default.nix
modules/flake-parts/website/render/default.nix

previously the options of other imported modules were not shown which gave an incomplete picture. For example the docs page for the `pip` module did not show the options prefixed with `mkDerivation` which are accepted and needed by the pip module.
It's better to have everything on one page for each module.

docs: don't strip foreign module options

---

CHANGELOG.md
examples/packages/languages/python-local-development-multiple-packages/default.nix
examples/packages/languages/python-packaging-apache-airflow/default.nix
examples/packages/languages/python-packaging-odoo/default.nix
lib/internal/mkSubmodule.nix
modules/dream2nix/nodejs-granular-v3/default.nix
modules/dream2nix/nodejs-granular-v3/interface.nix
modules/dream2nix/overrides/default.nix
modules/dream2nix/overrides/interface.nix
modules/dream2nix/php-granular/default.nix
modules/dream2nix/php-granular/interface.nix
modules/dream2nix/pip/default.nix
modules/dream2nix/pip/interface.nix
modules/flake-parts/website/default.nix

Add options `overrides.${name}` and `overrideAll` to all language modules that manage a dependency tree.
This is done in a backward compatible fashion. Old options for overriding dependencies continue working, though those are not displayed in the manual anymore.
For the following modules the manual now suggest using the new unified override options:
- for pip: use `pip.overrides` and `pip.overrideAll` instead of  `pip.drvs`
- for nodejs-granular-v3: use `nodejs-granular-v3.overrides` and `nodejs-granular-v3.overrideAll` instead of `nodejs-granular-v3.deps`
- `php-granular`: use `php-granular.override` and `php-granular.overrideAll` instead of `php-granular.deps`

override: unify overriding across modules

---

examples/packages/languages/python-local-development-machine-learning/default.nix
examples/packages/languages/python-packaging-apache-airflow/default.nix
overrides/python/pillow/default.nix
overrides/python/psycopg2/default.nix

Those are not needed anymore since the hook has been improved in nixpkgs

python: remove catchConflicts = false overrides

---

modules/dream2nix/WIP-groups/groups-option.nix
modules/dream2nix/WIP-groups/interface.nix
modules/dream2nix/WIP-python-pdm/default.nix
modules/dream2nix/WIP-python-pdm/interface.nix

The most important feature of the groups module was the overriding which is a separate module now. Therefore removing the fact that groups are used from the docs to decrease the API surface to maintain.
Instead render the override and overrideAll options in the manual of pdm correctly by setting `overrideType`.

python/pdm: hide groups as implementation detail

---

modules/dream2nix/mkDerivation/interface.nix

:wave: 
This fixes a typo I've encountered through https://github.com/yusdacra/nix-cargo-integration, which uses dream2nix.

mkDerivation: fix typo in checkFlags

---

overrides/python/opencv-python/default.nix

Adds qt support for opencv-python
(Currently fails with the classic QPA Plugin Error).

overrides/python: Adds qt support for opencv

---

modules/dream2nix/WIP-haskell-cabal/lock.py

Fetch cabal revisions from `https://hackage.haskell.org/package/{name}-{version}/revisions/`, rather than `https://hackage.haskell.org/package/{name}/revisions/`, which fetches revisions for the latest package version, not the version pinned in `./dist-newstyle/cache/plan.json`.
Before
```bash
$ nix run github:lbodor/gamgee?ref=dream2nix#gamgee.lock
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date.
The index-state is set to 2024-03-27T00:32:46Z.
Resolving dependencies...
Wrote freeze file: /tmp/tmp.7Waiw8oj27/cabal.project.freeze
[1/48] Resolving revision for Hclip
[2/48] Resolving revision for OneTuple
[3/48] Resolving revision for QuickCheck
[4/48] Resolving revision for aeson
Could not find revision for aeson-1.5.6.0
...
``` …

WIP-haskell-cabal: fetch correct cabal revisions

---

modules/dream2nix/WIP-python-pdm/default.nix

`public.pyEnv` can be used as `runtimeInputs` in other applications. You can find one such example [here](https://github.com/shivaraj-bh/ollama-flake/blob/7b6375cc4849c6b3a91be5543043d3c820d312f6/nix/ollama.nix#L52).

`WIP-python-pdm`: add `public.pyEnv`; reuse `public.pyEnv` in `public.devShell`

---

modules/dream2nix/WIP-python-pdm/lock.nix

Changes config.deps.python3 reference in lock.nix to config.deps.python. 
Fixes https://github.com/nix-community/dream2nix/issues/885 and https://github.com/nix-community/dream2nix/issues/911

python/pdm: Changes deps.python3 refs to deps.python

---

examples/packages/languages/python-local-development/default.nix
examples/packages/languages/python-local-development/flake.nix
examples/packages/languages/python-local-development/lock.json
examples/packages/languages/python-local-development/my_tool/__init__.py
examples/packages/languages/python-local-development/pyproject.toml
modules/dream2nix/buildPythonPackage/interface.nix
modules/dream2nix/pip/default.nix
modules/dream2nix/pip/editable.nix
modules/dream2nix/pip/editable.py
modules/dream2nix/pip/interface.nix
pkgs/fetchPipMetadata/package.nix
pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
pkgs/fetchPipMetadata/src/tests/test_lock_entry_from_report_entry.py
pkgs/fetchPipMetadata/src/tests/test_lock_file_from_report.py

Hello,
This is a PR which implements devshells with support for console scripts and richer metadata then the approach in https://github.com/nix-community/dream2nix/pull/912. Its currently only implemented for the pip builder, but the idea should be portable to PDM as well. Planning to look into this soon.
*  users need to declare an the root package and/or dependencies of a given python project as editable. Consider a devshell for a package named `my-tool`:
```nix
{
pip.editables.charset-normalizer = "/home/my-user/src/charset-normalizer";
pip.editables.click = null;
pip.editables.my-tool = null;
}
```
The first expression would link the editable `charset-normalizer` from the given absolute path, to `.dream2nix/editables/charset-normalizer` and install it.
The second line would default to …

Python DevShells (for pip)

---

modules/dream2nix/buildPythonPackage/interface.nix

https://github.com/NixOS/nixpkgs/pull/271597 implemented a new format for python packages that is starting to get traction in nixpkgs/unstable (soon to become NixOS 24.05).
That is a progress towards https://github.com/NixOS/nixpkgs/issues/272178, which would be a massive improvement for dream2nix once completed.
This first step just makes sure that `buildPythonPackage` supports the new arguments properly. Without this change, many dream2nix python derivations fail to build on nixos-unstable right now.
Probably other python auto-builders should leverage these new options when available for the d2n user. That can be added later.
@moduon MT-1075

feat(buildPythonPackage): support new pyproject format

---

pkgs/fetchPipMetadata/filter-pypi-responses.py

mitmproxy was buffering all requests (except pythonhosted.*), causing pip to time out when getting big packages from custom URLs.
Setting flow.response.stream in the responseheaders hook fixes this.

filter-pypi-responses: stream package requests that hit the proxy

---

examples/packages/languages/python-local-development-multiple-packages/default.nix
examples/packages/languages/python-local-development-pdm/default.nix
examples/packages/languages/python-local-development/default.nix
examples/packages/languages/python-packaging-apache-airflow/default.nix
modules/dream2nix/WIP-python-pdm/default.nix
modules/dream2nix/WIP-python-pyproject/default.nix
modules/dream2nix/pip/default.nix
modules/dream2nix/pip/tests/packages/can-build-setuptools/default.nix
modules/dream2nix/pip/tests/packages/can-handle-setuptools-runtime-dep/default.nix
pkgs/fetchPipMetadata/package.nix

It's important to get the default in our PDM module fixed, because upstream documentation recommends using pyproject = true; and ships an assertion assertion '((pyproject != null) -> (format == null))' that fails with the current default in pdm.

treewide: format = "pyproject" -> pyproject = true

---

modules/dream2nix/WIP-python-pdm/default.nix

I doubt this is an ideal implementation, but I'm hoping that an imperfect incremental improvement to a WIP module is acceptable :) 
When I took a look at switching a project that uses a private package from the pip to WIP pdm module, I noticed that pdm did pick up the alternate index when I imported the requirements. They look something like:
```toml
[[tool.pdm.source]]
name = "some hash or random identifier pdm generated"
url = "https://some-other-index.example.com/"
verify_ssl = true
``` 
I looked into how to leverage it in dream2nix and saw at least two paths:
1. Let pdm deal with this at lock time by using the `static_urls` locking strategy so that it locks a full index-specific url for each ~file.
2. Since `fetchFromLegacy` already supports a single url or a list of urls, just …

pdm: support additional index/source URLs

---

docs/src/.pages
docs/src/gettingstarted.md
docs/src/guides/.pages
docs/src/guides/getting-started.md

Our getting started guide previously mostly showed a template but didn't explain too much what's happening. I tried to improve that using [code annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/). 
Happy for any feedback, especially from people who do not have too much experience with nix & dream2nix yet as you are the target audience :)
I am also working on a Python & Pip guide, hope to push that one soonish.

Reworked Getting started guide

---

docs/hooks/render_options.py
docs/theme/reference_options.html
modules/dream2nix/WIP-groups/README.md
modules/dream2nix/buildPythonPackage/README.md
modules/dream2nix/buildRustPackage/README.md
modules/dream2nix/builtins-derivation/README.md
modules/dream2nix/core/README.md
modules/dream2nix/mkDerivation/README.md
modules/dream2nix/multi-derivation-package/README.md
modules/dream2nix/nixpkgs-overrides/README.md
modules/dream2nix/nodejs-devshell-v3/README.md
modules/dream2nix/nodejs-devshell/README.md
modules/dream2nix/nodejs-granular/README.md
modules/dream2nix/nodejs-node-modules-v3/README.md
modules/dream2nix/nodejs-node-modules/README.md
modules/dream2nix/nodejs-package-json/README.md
modules/dream2nix/nodejs-package-lock/README.md
modules/dream2nix/overrides/README.md
modules/dream2nix/package-func/README.md
modules/dream2nix/rust-cargo-lock/README.md
modules/dream2nix/rust-crane/README.md

- **reference website: render all options with same heading size**
- **reference website: categorize into released/experimental/internal**

referece docs: categorize modules

---

docs/src/style.css
docs/theme/partials/toc-item.html

- increase width of toc
- show full option path in toc
- no nesting
This simplifies navigation on option pages a lot.

docs: improve table of contents for options

---

docs/hooks/render_options.py
modules/flake-parts/reference-website/default.nix

remove tree-style preprocessing since it is not needed anymore

reference-docs: fix option rendering issue

---

flake.lock
modules/dream2nix/WIP-python-pdm/default.nix
modules/dream2nix/WIP-python-pdm/lock.nix

PDM now experimentally supports a [uv resolver](https://github.com/pdm-project/pdm/pull/3144). This is significantly faster(even on the examples with very few dependencies, resolve times go from a few seconds to a few hundred milliseconds). This PR enables the use of that resolver. 
note that nixpkgs needs to be updated due to only the newer versions of pdm supporting it.
@DavHau @phaer

Adds uv resolver for pdm

---

modules/dream2nix/rust-crane/default.nix

this fixes [this](https://github.com/oxalica/rust-overlay/issues/153) error from occurring (and is also a better API anyway, just providing a cargo was pretty hacky)

refactor(rust-crane): don't overlay the pkgs for crane, use the overrideToolchain api instead

---

modules/dream2nix/rust-crane/default.nix
modules/dream2nix/rust-crane/interface.nix

removes the crane option because it was not used anymore, and doesn't make sense to keep regardless (can just override the package, there should not be any need to modify the crane functions other than changing the source used for crane)

fix(rust-crane): add mkRustToolchain to interface options, define a proper default, pass toolchain to vendor and devshell

---

modules/dream2nix/rust-crane/default.nix
modules/dream2nix/rust-crane/interface.nix

- adds `buildCommand`, `checkCommand` and `testCommand` for changing the cargo subcommands used

feat(rust-crane): add options for changing build, check and test cargo subcommands

---

modules/dream2nix/rust-crane/default.nix
modules/dream2nix/rust-crane/interface.nix

exposing this is useful since downstream can just use the crane lib dream2nix creates instead of using their own if they want to do something with it

feat(rust-crane): expose the crane lib that is created from craneSource as a read-only option

---

modules/dream2nix/rust-cargo-lock/translate.nix

this caused `getNodeFromPath` to error out with `failed to navigate to path`, so we fix it (i'm not sure why it does that but removing it is a good idea anyway since it keeps things consistent)

fix(rust-cargo-lock): remove leading period from any workspace member relative paths

---

modules/dream2nix/WIP-python-pdm/interface.nix
modules/dream2nix/WIP-python-pdm/lock.nix

Makes use of uv resolver optional per https://github.com/nix-community/dream2nix/pull/1067#issuecomment-2552461148
@phaer

pdm: Makes uv resolver optional

---

modules/dream2nix/WIP-python-pdm/lib.nix

Fixes key error where natural sort from `sources` & `version` doesn't match the original `extras` key order

natural sort extras in mkDepEntry

---

overrides/rust/jack-sys/default.nix

I added a dependency override for the `jack-sys` rust crate. Let me know if I did something wrong because I'm pretty new to dream2nix (and also contributing to open source) but I think this is correct as far as I can tell.

added jack-sys dependency override for rust

---

modules/dream2nix/nodejs-granular-v3/default.nix
modules/dream2nix/nodejs-package-lock-v3/default.nix

This is in fact the default behavior with e.g. npx create-remix. Previously, if you created a package with that command and tried running dream2nix, you'd get a missing attribute error.

Allow not setting version in package.json

---

modules/dream2nix/nodejs-granular/default.nix
modules/dream2nix/nodejs-granular/interface.nix

This feature [already exists in nodejs-granular-v3](https://github.com/nix-community/dream2nix/blob/995e831dac8c2c843f1289d15dfec526cb84afdd/modules/dream2nix/nodejs-granular-v3/interface.nix#L14-L17), I took it from there.

nodejs-granular: allow overrides for specific and all `nodejsDeps`

---

pkgs/fetchPipMetadata/script.nix

Allows user to have spaces in the project root path, fixes #795

fix(fetchPipMetadata): quote path arguments to fetch_pip_metadata script

---

overrides/python/certifi/default.nix

python / certifi comes with its own certificate store. nixpkgs applies a patch by default to use NIX_SSL_CERT_FILE instead
https://github.com/NixOS/nixpkgs/blob/ad331efcaf680eb1c838cb339472399ea7b3cdab/pkgs/development/python-modules/certifi/default.nix#L25-L34

override: python certifi

---

modules/dream2nix/python-pdm/default.nix
modules/dream2nix/python-pdm/interface.nix
modules/dream2nix/python-pdm/tests/packages/python-local-development/default.nix
modules/dream2nix/python-pdm/tests/packages/python-local-development/pyproject.toml

the advantage of PDM and its single lockfile is a single point of truth, for multiple architectures and multiple use cases (groups).
The groups feature should get leveraged, in order to have different types of python, e.g. python used for tests, python used for runtime only.
Therefore the group which should get used should be configurable. Closes https://github.com/nix-community/dream2nix/issues/1093
modules/dream2nix/python-pdm/tests/packages/python-local-development:

pdm: group name

---

CHANGELOG.md
modules/dream2nix/package-func/README.md
modules/dream2nix/package-func/default.nix

This commit modifies the package-func module to use the first output in
`package-func.outputs` or the default output (if the attribute `outputSpecified`
is true) as the top-level output in the final package instead of throwing
an error for multi-output derivations. Documentation for structure of the
assembled package and the selection criterion for the top-level output added
to the README.md under the module directory. In addition, a changelog entry
was appended to CHANGELOG.md to record this change.

package-func: select first output in outputs for multi-output derivations

---

README.md

This link is dead when clicked from dream2nix.dev. Make it point to actual documentation. Closes #842

Redirect "To the docs" link to "Getting Started"

---

modules/flake-parts/reference-website/default.nix

This is better, as people might want to keep the original docs website open

docs: open options in new tab
