README.md, flake.lock, flake.nix, notes/node2nix.md, specifications/generic-lock-example.json, specifications/generic-lock-schema.json, specifications/subsystems/nodejs/dream.lock.example.json, specifications/translator-call-example.json, src/apps/cli.py, src/apps/default.nix, src/builders/default.nix, src/builders/nodejs/node2nix/default.nix, src/builders/python/simple-builder/default.nix, src/config.json, src/default.nix, src/fetchers/combined-fetcher.nix, src/fetchers/default-fetcher.nix, src/fetchers/default.nix, src/translators/default.nix, src/translators/nodejs/pure/npmlock2nix/default.nix, src/translators/python/impure/pip/default.nix, src/translators/python/impure/pip/generate-generic-lock.py
Nodejs:
- finalizing nodejs support by integrating the node2nix builder
Python:
- improve builder
- add support for python applications
Framework improvements:
- automatically remove cyclic dependencies
- autoselect translator
- differentiate between input files and directories
- allow translators to declare special arguments
- allow sources to be unknown (have to be overridden by user)
- rename: generic lock -> dream lock
- add framework config file for central flags like 'allowBuiltinFetchers'
- handle github sources without hash
=> nodejs support + framework improvements

docs/concepts-and-benefits.md, docs/nixpkgs-improvements.md, flake.nix, src/apps/cli/commands/package.py, src/apps/cli/commands/update.py, src/apps/cli/default.nix, src/apps/cli/utils.py, src/apps/contribute/contribute.py, src/builders/nodejs/granular/default.nix, src/builders/nodejs/node2nix/default.nix, src/builders/python/simple-builder/default.nix, src/default.nix, src/fetchers/combined-fetcher.nix, src/fetchers/default-fetcher.nix, src/specifications/dream-lock-example.json, src/specifications/dream-lock-schema.json, src/specifications/subsystems/nodejs/dream.lock.example.json, src/specifications/translator-call-example.json, src/templates/translators/pure.nix, src/translators/default.nix, src/translators/nodejs/pure/package-lock/default.nix, src/translators/nodejs/pure/yarn-lock/default.nix, src/translators/python/impure/pip/default.nix, src/translators/python/impure/pip/generate-dream-lock.py, src/utils/default.nix, src/utils/dream-lock.nix, src/utils/translator.nix
New dream lock format is optimized for:
- human readability
- can be parsed efficiently by nix (without having to transform a lot of structures)
dream lock file is now renamed to `dream-lock.json`
=> Refactor/Improve dream-lock structure

src/apps/cli/commands/add.py, src/apps/cli/default.nix, src/default.nix, src/fetchers/combined-fetcher.nix, src/fetchers/default-fetcher.nix, src/fetchers/http/default.nix, src/translators/nodejs/pure/package-lock/default.nix, src/translators/python/impure/pip/generate-dream-lock.py, src/utils/default.nix, src/utils/dream-lock.nix, src/utils/translator.nix, tests/impure/default.nix, tests/impure/test_combined_fetching.nix, tests/pure/default.nix, tests/pure/other/default.nix, tests/pure/other/prettier-github-aggregated.json, tests/pure/other/prettier.json, tests/pure/projects.nix
- aggregated fetcher now uses `async`. It's still annoyingly slow. Could try gnu-parallel.
- fix some other bugs
=> Improve aggregated source fetching + fix some bugs

overrides/nodejs/default.nix
Since recently, dream2nix also executes the `install` script defined in a projects `package.json` which is required for correctly building some dependencies.
This might have been the reason why ledger-live-desktop did not build.
Running the install script now triggered some more failures in dependencies of ledger-live-desktop. Some of those are fixed via overrides.
Currently it is stuck at building ledger-core, since the cmake tries to pull stuff from github.
Maybe you can progress from here @asymmetric
=> progress ledger-live-desktop

src/builders/rust/build-rust-package/default.nix
=> fix(rust): write cargo checksum for path dependencies

src/builders/rust/build-rust-package/default.nix, src/builders/rust/vendor.nix
These are extracted from #83 since they are unrelated to that PR.
Fixes #86
=> fix(rust): some rust builder improvements

overrides/nodejs/default.nix
Just adds an override for esbuild 0.14.
I'll add more of those if that works for you.
=> ebuild  0.14

README.md
just add an example to the readme with special characters in it.
feel free to add/remove/do whatever you like, this is just a proposal, I don't care if you make a different commit yourself where you change the wording.
=> Readme add example

overrides/nodejs/default.nix
just adding version 0.13 override
=> esbuild: add 0.13 override

src/builders/rust/build-rust-package/default.nix, src/builders/rust/crane/default.nix, src/builders/rust/vendor.nix, src/discoverers/rust/default.nix, src/translators/rust/pure/cargo-lock/default.nix
This WIP PR implements a way to fix #113. As mentioned in #114's last comments. Note this doesn't work yet, I'm just putting this here so it is seen.
@DavHau would be nice if you could take a look at this, and see the general gist of what I meant in my comment on #114.
=> Attempt to fix #113

src/fetchers/git/default.nix, src/specifications/dream-lock-schema.json, src/translators/rust/pure/cargo-lock/default.nix
=> feat: allow ref to be specified in git source

src/subsystems/rust/builders/utils.nix
This fixes an issue with the Cargo.lock generated package entries having out of sync git sources with the Cargo.toml. If a `rev`, `branch` or `tag` is not specified in the Cargo.toml, we should not default to `rev`, this fixes that.
=> fix(rust/builders): dont default to rev as ref part while generating Cargo.lock

docs/src/SUMMARY.md, docs/src/development-roundups.md, docs/src/development-roundups/2022-april-june.md, docs/src/intro.md
@yusdacra If you feel like something is missing, feel free to add stuff and push to this branch.
=> Add development roundup April - June

flake.nix, src/default.nix, src/lib/default.nix, src/lib/modules.nix, src/utils/index.nix, tests/examples/default.nix
See https://github.com/NixOS/nixos-search/pull/502#issuecomment-1193305553 and the discussion there.
=> fix: make dream2nix evaluation work with --read-only flag

src/apps/translate-index/default.nix, src/fetchers/default-fetcher.nix, src/indexers/libraries-io/default.nix, src/specifications/dream-lock-schema.json, src/subsystems/nodejs/builders/granular/default.nix, src/subsystems/nodejs/translators/package-json/default.nix, src/subsystems/nodejs/translators/package-lock/default.nix, src/subsystems/nodejs/translators/utils.nix, src/utils/default.nix, src/utils/dream-lock.nix, src/utils/index.nix
Done: See commit messages
With this, dream2nix-npm now works on the 100 most popular packages without any translation or eval errors
=> Imrovements for: nodejs, translators, indexers

flake.lock, flake.nix, src/default.nix, src/fetchers/crates-io/default.nix, src/subsystems/haskell/builders/default/default.nix, src/subsystems/haskell/translators/stack-lock/default.nix, src/subsystems/haskell/translators/stack-lock/utils.nix, src/subsystems/nodejs/builders/granular/default.nix, src/subsystems/rust/builders/vendor.nix, src/utils/default.nix, src/utils/external-dir.nix
- use runCommandLocal to speed up builds and keep caches cleaner
- remove unused node2nix
=> Some fixes

src/subsystems/nodejs/translators/yarn-lock/default.nix
Just a misspelling of the attribute name
=> Fix attribute name

docs/src/SUMMARY.md, docs/src/define-targets.md, docs/src/guides/getting-started-nodejs.md, docs/src/guides/getting-started-python.md, docs/src/install-nix.md, docs/src/intro/fetchers.md
=> docs: add `Fetchers` section to docs

overrides/nodejs/default.nix
Depends on https://github.com/NixOS/nixpkgs/pull/188710, already merged.
=> nodejs/electron: add 20.1.0

flake.lock, flake.nix, src/default.nix, src/subsystems/rust/builders/build-rust-package/default.nix, src/subsystems/rust/builders/crane/default.nix, src/subsystems/rust/builders/vendor.nix, src/subsystems/rust/translators/cargo-lock/default.nix
…improve path dependency replacement to not include full source in more situations
=> fix(rust): update crane, fix build issues

docs/src/subsystems/php.md, src/lib/builders.nix, src/subsystems/php/builders/granular/default.nix, src/subsystems/php/builders/granular/devShell.nix, src/subsystems/php/builders/simple/default.nix, src/subsystems/php/builders/simple/devShell.nix
Towards #240 
After #296
Add a granular builder.
=> php: granular builder

overrides/nodejs/default.nix
- https://github.com/NixOS/nixpkgs/pull/191834
=> nodejs/electron: 20.1.0 -> 20.1.3

flake.nix, src/default.nix, src/subsystems/rust/builders/build-rust-package/default.nix, src/subsystems/rust/builders/crane/default.nix, src/subsystems/rust/builders/devshell.nix, src/subsystems/rust/builders/vendor.nix
Replaces Rust devshells to use numtide's devshell.
=> feat: use devshell for rust devshells

src/apps/default.nix, src/apps/replaceRootSources/default.nix, src/apps/replaceRootSources/replaceRootSources.py, src/subsystems/php/translators/packagist/default.nix, src/subsystems/rust/translators/crates-io/default.nix
Replace a call to `callNixWithD2N` with a python script.
=> Speed up indexers

overrides/nodejs/default.nix
Depends on:
- https://github.com/NixOS/nixpkgs/pull/194289
=> nodejs/electron: add 21.0.1

.github/workflows/tests.yml, flake.lock, src/subsystems/haskell/builders/simple-haskell/default.nix, src/subsystems/haskell/translators/stack-lock/utils.nix
The jailbreak check in nixpkgs is not reproducible. See See https://github.com/NixOS/nixpkgs/issues/151347#issuecomment-1278217978
It's probably better to disable it altogether.
=> Haskell: enable jailbreak by default

flake-compat.nix, flake.lock, flake.nix, src/default.nix, src/lib.nix, src/modules/top-level.nix, src/subsystems/haskell/translators/stack-lock/default.nix, src/subsystems/haskell/translators/stack-lock/utils.nix, src/subsystems/haskell/translators/utils.nix
related: https://github.com/nix-community/dream2nix/pull/328
=> chore: manage all-cabal-json via flake input

examples/_d2n-flake-parts/flake.nix, flake.nix, src/lib/default.nix, src/modules/flake-parts/default.nix, src/modules/flake-parts/implementation.nix, src/modules/flake-parts/interface.nix, src/subsystems/rust/builders/devshell.nix
Implements a flake-parts module.
=> feat: add a flake-parts module

overrides/nodejs/default.nix
- https://github.com/NixOS/nixpkgs/pull/199188
=> nodejs/electron: add 21.2.1

examples/haskell_cabal-freeze/flake.nix, src/subsystems/haskell/translators/cabal-freeze/default.nix, src/subsystems/haskell/translators/cabal-freeze/parser.nix
I had these changes but didn't get around to pushing them prior to the last merge, sorry.
=> cabal-freeze improvements

src/modules/config/interface.nix
=> fix: Added type check for packagesDir option

flake.nix
=> add all examples as templates

src/subsystems/python/translators/poetry/default.nix
https://github.com/python-poetry/poetry/commit/41706e649cf3ee9b066c59920b4e10e686f8c6d5 broke the parser.
Poetry changed it's lock file structure some time ago.
This fixes the translator crashing on the new format
@phaer
=> fix: python: poetry: incompatible with newer version of poetry.lock

overrides/nodejs/default.nix
- https://github.com/NixOS/nixpkgs/pull/204464
=> nodejs/electron: add 22.0.0

overrides/nodejs/default.nix
hey just testing things out with a new project, and ran into a missing electron.
hope you are well!
=> chore: nodejs: add electron 19.1.9

docs/src/define-targets.md, src/lib.nix
Easy to miss for beginning users :)
=> Document adding `project.toml` to git more explicitly

v1/nix/modules/drv-parts/buildPythonPackage/interface.nix
This adds makeWrapperArgs from nixpkgs buildPythonPackage to our options.
=> feat(v1/buildPythonPackage): add makeWrapperArgs

v1/nix/modules/drv-parts/lock/default.nix
... and delete ones which became empty
=> feat(lock): don't write empty lock file

.github/workflows/tests.yml, v1/nix/modules/drvs/isso/lock-x86_64-linux.json, v1/nix/modules/drvs/nodejs-no-lock/lock-x86_64-linux.json
... also stop running `.#update-locks` in CI.
=> update all lock files in `v1/nix/modules/drvs`

v1/nix/modules/drvs/odoo/default.nix
...to fix aarch64-darwin builds
=> v1/drvs: add nixpkgs-overrides for odoos psycopg2

README.md
- remove legacy examples + example tests
- readme: add notice for legacy interface
=> legacy notice

README.md, ci.nix, examples/dream2nix-repo/default.nix, examples/dream2nix-repo/packages/hello/default.nix, examples/dream2nix-repo/settings.nix
An example for a dream2nix repo with multiple packages
=> examples: add dream2nix-repo

modules/flake-parts/writers.nix, pkgs/writers/default.nix
- Add module docs for writers
- chore: format
=> reformatted #597

README.md, docs/src/SUMMARY.md, docs/src/examples.md, examples/dream2nix-repo/default.nix
- examples: improve dream2nix-repo example
- docs: link examples from the docs
=> docs: link to examples

pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
- ~~fetchPipMetadata: avoid deprecation warning~~
- fetchPipMetadata: compute hash for non-FOD paths
=> fetchPipMetadata: fixes

modules/default.nix, modules/flake-parts/all-modules.nix, modules/flake.nix
- all-modules: ignore files in module directory
- modules: add standalone flake
=> add standalone flake for modules (no inputs)

modules/dream2nix/pip/default.nix, pkgs/fetchPipMetadata/fetchPipMetadata.nix, pkgs/fetchPipMetadata/package.nix, pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py, pkgs/fetchPipMetadata/src/shell.nix, pkgs/fetchPipMetadata/src/tests/test_lock_entry_from_report_entry.py, pkgs/fetchPipMetadata/src/tests/test_lock_file_from_report.py, pkgs/fetchPipMetadata/src/tests/test_lock_info_from_path.py
Reverts nix-community/dream2nix#620
=> Revert "Support git repositories in fetchPipMetadata"

lib/internal/nodejsLockUtils.nix, modules/dream2nix/nodejs-package-lock-v3/default.nix, modules/dream2nix/nodejs-package-lock-v3/interface.nix, modules/flake-parts/checks.nix-unit.nix, tests/nix-unit/test_nodejs_lock_v3/default.nix, tests/nix-unit/test_nodejs_lock_v3/lib/package.json, tests/nix-unit/test_nodejs_lock_v3/package-lock.json, tests/nix-unit/test_nodejs_lockutils/default.nix, tests/nix-unit/test_nodejs_lockutils/package-lock.json
@DavHau WIP,
All tests work.
Somehow i get infinite recursion erorr, when trying to reference the fetchurl derivation (source) of a pdef
=> WIP: init: package-lock.json V3 parser

examples/dream2nix-repo-flake/flake.nix, examples/dream2nix-repo/default.nix, modules/flake-parts/lib.nix
This makes the repo initialization simpler (see examples)
=> feat(lib): add helper lib.importPackages

examples/packages/single-language/rust-package/default.nix, modules/dream2nix/buildRustPackage/default.nix, modules/dream2nix/buildRustPackage/patch-workspace-deps.jq, modules/dream2nix/buildRustPackage/utils.nix, modules/dream2nix/rust-crane/default.nix, modules/dream2nix/rust-crane/devshell.nix, modules/dream2nix/rust-crane/utils.nix
- feature: add devshell to rust-crane packages
- fix: add patch workspace deps to buildRustPackage
=> feat(rust-crane): add devshell to packages

modules/dream2nix/WIP-python-pyproject/default.nix
The heuristic was not reliable
=> fix(python-pyproject): remove default for pythonImportsCheck

examples/packages/single-language/python-machine-learning/default.nix, modules/dream2nix/pip/default.nix, modules/flake-parts/lib.nix, modules/flake-parts/overrides.nix, overrides/python/torch/default.nix, overrides/python/triton/default.nix
- Add community overrides accessible via dream2nix.overrides.{lang}.{pname}
- make the pip module use the overrides for dependencies
=> feat: community overrides

overrides/python/torch/default.nix
This allows resolving libcuda.so.1
=> feat(overlays/torch): add /run/opengl-driver/lib to RPATH

modules/dream2nix/core/lock/default.nix
This seems like a cleaner way to make the value for lock.content more lazy and not trigger errors because paths.XXX is not set in unit tests
=> refactor(lock): introduce mkLazy

examples/packages/multi-language/python-nodejs/lock.json, examples/packages/single-language/python-machine-learning/lock.json, examples/packages/single-language/python-package-ansible/lock.json, examples/packages/single-language/python-package-apache-airflow/lock.json, examples/packages/single-language/python-package-odoo/lock.json, examples/packages/single-language/python-package-pillow/lock.json, examples/packages/single-language/python-project/lock.json, flake.lock, modules/dream2nix/php-granular/default.nix, modules/dream2nix/pip/default.nix
we now depend on lib.path functions
=> update nixpkgs input

examples/dream2nix-repo-flake-pdm/flake.nix, modules/dream2nix/WIP-python-pdm/default.nix, modules/dream2nix/WIP-python-pdm/fetch-from-pypi.nix, modules/dream2nix/WIP-python-pdm/fetch-from-pypi.sh, modules/dream2nix/groups/group.nix, modules/dream2nix/groups/interface.nix, modules/flake-parts/examples.nix, tests/nix-unit/test_groups/default.nix
Also implement source fetching
=> feat(pdm): build default group

examples/dream2nix-repo-flake/flake.nix
=> fix: nixpkgs follows d2n

modules/flake-parts/checks.nix, pkgs/fetchPipMetadata/package.nix
- checks: add all packages to checks
- fetch-pip-metadata: fix build
=> fetch-pip-metadata: fix build

modules/dream2nix/pip/default.nix, modules/dream2nix/pip/interface.nix, pkgs/fetchPipMetadata/script.nix
This helps for configuring pip with environment variables. See https://github.com/nix-community/dream2nix/discussions/697 for more context.
pip: remove callPackage
=> feat: allow specifying env for fetchPipMetadata

modules/dream2nix/WIP-python-pdm/lib.nix
At least a temporary fix for https://github.com/nix-community/dream2nix/issues/743.
=> fix(pdm): Make parsed_deps lowercase

modules/dream2nix/WIP-python-pdm/default.nix, modules/dream2nix/groups/group.nix, tests/nix-unit/test_groups/default.nix, tests/nix-unit/test_python-pdm/default.nix
renames:
- packages.foo."1.0.0" -> packages.foo."1.0.0".conf
- packagesEval.foo."1.0.0" -> packages.foo."1.0.0".evaluated
- public.packages.foo."1.0.0" -> packages.foo."1.0.0".public
=> groups: change structure

modules/dream2nix/WIP-python-pdm/default.nix, modules/dream2nix/WIP-python-pdm/lib.nix, modules/dream2nix/groups/group.nix, modules/dream2nix/groups/interface.nix, tests/nix-unit/test_groups/default.nix, tests/nix-unit/test_python-pdm-lib/default.nix
- groups: rename commonModule -> overrideAll
- pdm: reformat lib.nix
- pdm: allow selecting multiple groups
=> pdm: multiple groups + refactoring

modules/dream2nix/WIP-spago/interface.nix, modules/dream2nix/groups/interface.nix, modules/flake-parts/render/default.nix
- docs: fix missing options for modules
- docs: improve docs for groups
=> docs: fix missing options for modules

modules/dream2nix/buildRustPackage/utils.nix, modules/dream2nix/buildRustPackage/vendor.nix, modules/dream2nix/rust-crane/crane.nix, modules/dream2nix/rust-crane/default.nix, modules/dream2nix/rust-crane/utils.nix, modules/dream2nix/rust-crane/vendor.nix
- support crane v0.15.0
- fix discrepancy with dream2nix generated Cargo.lock
- print more informational messages when building
=> feat(rust): update & support crane version v0.15.0, fix some issues

dev-flake/flake.lock, dev-flake/flake.nix, modules/dream2nix/WIP-python-pdm/default.nix, modules/dream2nix/WIP-python-pdm/interface-dependency.nix, modules/dream2nix/WIP-python-pdm/lib.nix, modules/dream2nix/WIP-python-pdm/sourceSelectorOption.nix, tests/nix-unit/test_python-pdm-lib/default.nix
- implement per dependency sourceSelector option
- update pyproject.nix
- update nix-unit
=> python/pdm: improve implementation and UI

modules/flake-parts/render/default.nix, modules/flake-parts/site/default.nix
...instead use internal options to pass the module docs pages to the renderer
=> docs: remove spam from flake-outputs

modules/dream2nix/WIP-python-pdm/default.nix
...until https://github.com/nix-community/pyproject.nix/pull/41 is resolved
=> python/pdm: use fetchFromLegacy

flake.lock, flake.nix
... until the open PRs are merged
=> pyproject.nix: switch to dream2nix fork

modules/dream2nix/pip/tests/packages/can-build-setuptools/default.nix, modules/dream2nix/pip/tests/packages/can-build-setuptools/flake.nix, modules/dream2nix/pip/tests/packages/can-build-setuptools/lock.json, modules/dream2nix/pip/tests/packages/can-build-setuptools/my_tool/__init__.py, modules/dream2nix/pip/tests/packages/can-build-setuptools/pyproject.toml
to ensure that a setuptools dependency doesn't raise a collision
=> pip: add test can-build-setuptools

modules/dream2nix/WIP-python-pdm/lock.nix
--refresh only works well with already existing lock files
=> pdm: lock fully, remove --refresh

modules/dream2nix/WIP-nodejs-builder-v3/default.nix
This fixes issues with unpacking inconsistent archive structures in the npm registry
This is a small piece of the bigger PR #757  that we can already merge.
@DavHau  what do you think
=> add custom unpackPhase from the original nodejs builder

lib/internal/graphUtils.nix, modules/dream2nix/WIP-nodejs-builder-v3/default.nix, modules/dream2nix/WIP-nodejs-builder-v3/interface.nix, modules/dream2nix/WIP-nodejs-builder-v3/types.nix, modules/dream2nix/WIP-nodejs-builder-v3/utils.nix, tests/nix-unit/test_graph_utils/fileSystem.nix
- simplify graph methods & add more tests for fileSystem
=> simplify & test lockv3 graph methods 

flake.lock
Reverts nix-community/dream2nix#844
Broke .lock script for pip
=> Revert "update nixpkgs"

modules/flake-parts/site/src/SUMMARY.md, modules/flake-parts/site/src/contact.md, modules/flake-parts/site/src/gettingstarted.md
I always forget how to get going with dream2nix, and while this page doesn't contain much more than you'd already find in the examples, I do think it's a good starting point for allowing people to start more confidently.
=> Getting started docs

modules/dream2nix/WIP-nodejs-builder-v3/default.nix, modules/dream2nix/WIP-nodejs-builder-v3/modules/dist.nix, modules/dream2nix/WIP-nodejs-builder-v3/modules/installed.nix
- nodejs: move installation into derivation module
=> Nodejs: move installed into module

modules/dream2nix/WIP-nodejs-builder-v3/default.nix, modules/dream2nix/WIP-nodejs-builder-v3/scripts/install-trusted-modules.mjs
- nodejs: handle more npm dependency types
=> nodejs: handle more npm dependency types

modules/dream2nix/WIP-python-pdm/default.nix, modules/dream2nix/core/lock/default.nix
Also fix lock script to not swallow error messages
=> pdm: add rudimentary devShell

modules/dream2nix/WIP-groups/default.nix, modules/dream2nix/WIP-groups/group.nix, modules/dream2nix/WIP-groups/interface.nix
...since those are now managed by the dedicated overrides module
=> groups: remove options `overrides` and `overrideAll`

modules/dream2nix/WIP-python-pdm/lib.nix, modules/flake-parts/pythonEnv/default.nix, modules/flake-parts/pythonEnv/flake-template.nix
Add experimental one-liner command to create python environments.
```command
$ nix run github:nix-community/dream2nix#__pythonEnv requests whisper-ctranslate2
...
$ python -c "import requests; print('imported requests')"
imported requests
$ whisper-ctranslate2 --version
whisper-ctranslate2 0.4.1
```
=> pythonEnv: init

pkgs/fetchPipMetadata/script.nix, pkgs/fetchPipMetadata/src/fetch_pip_metadata/__init__.py
`pypiSnapshotDate` is a rather peculiar feature that allows users to check whether a lockfile it self can be reproduced. It's used less in internal examples than it had been before, and requires mitmproxy. Packaging for the latter has recently become more complicated and among other things inflates closure size quite a bit.
This PR aims to only add mitmproxy to the closure if `pypiSnapshotDate != null`. Please note that it's `null` already if the pip module with default arguments is used - the throw statement here seems to be an oversight.
=> fetchPipMetadata: make mitmproxy optional

docs/hooks/render_options.py
thanks @yorickvP for reporting this in
https://github.com/nix-community/dream2nix/pull/987
=> docs: fix incorrect option rendering for first children of nested options

pkgs/fetchPipMetadata/script.nix
to latest versions in nixpkgs unstable
=> fetchPipMetadata: update pip & wheel

README.md, docs/mkdocs.yml, docs/src/development-roundups/2022-april-june.md, docs/src/overrides.md, modules/flake-parts/reference-website/default.nix
- **Revert "website: revert back to nix-community.github.io/dream2nix"**
- **website: ensure CNAME file doesn't get removed**
=> website: fix dream2nix.dev domain

modules/dream2nix/rust-cargo-vendor/patch-workspace.jq, modules/dream2nix/rust-cargo-vendor/vendor.nix
this should fix more git dependencies that use workspace attributes
=> fix(rust-cargo-vendor): patch manifest attributes that use workspace.package aswell

modules/dream2nix/pip/default.nix
Fixes https://github.com/nix-community/dream2nix/issues/1071
=> pip: ignore collisions in pyEnv

pkgs/fetchPipMetadata/src/fetch_pip_metadata/__init__.py, pkgs/fetchPipMetadata/src/fetch_pip_metadata/lock_file_from_report.py
fixes https://github.com/nix-community/dream2nix/issues/745
copy store paths to tempdir and make them writable before executing pip
=> pip: fix could not create *.egg-info
